-- =============================================================================
-- review_pacing_presets + decks_with_stats review-pacing resolution
-- Introduced in 20260716000000_review-pacing-presets.sql,
--   20260716000002_decks-with-stats-review-pacing.sql
--
-- Covers:
--   1. one_system_review_pacing_preset partial unique index — only one
--      is_system = true row can ever exist.
--   2. RLS SELECT — a member sees the system preset + their own presets,
--      never another member's private preset.
--   3. RLS INSERT/UPDATE/DELETE — the system preset can never be edited,
--      deleted, or self-granted via is_system = true on insert.
--   4. decks_with_stats resolution ladder — override -> preset -> system,
--      resolved independently per field (desired_retention, learning_steps,
--      relearning_steps), including a deck with fields split across tiers.
--   5. desired_retention_override / learning_steps_override /
--      relearning_steps_override are surfaced as-is (NULL vs actual value).
--   6. Deleting a custom preset assigned to a deck SET NULLs the deck's FK
--      (not cascade, not error) and the deck resolves back to the system
--      preset's values.
--   7. Assigning another member's private preset to a deck does not leak
--      that member's preset values through decks_with_stats.
-- =============================================================================

BEGIN;

SELECT plan(27);

-- ── Setup (as postgres superuser) ─────────────────────────────────────────────

SELECT tests.create_user('a1111111-1111-1111-1111-111111111111'::uuid, 'alice_pacing');
SELECT tests.create_user('b2222222-2222-2222-2222-222222222222'::uuid, 'bob_pacing');

-- Test 1: the system preset seeded by the migration exists and is unique.
SELECT is(
  (SELECT count(*)::int FROM public.review_pacing_presets WHERE is_system),
  1,
  'exactly one system preset exists after the seed migration'
);

-- Test 2: the partial unique index rejects a second is_system = true row.
SELECT throws_ok(
  $$
    INSERT INTO public.review_pacing_presets
      (member_id, name, desired_retention, learning_steps, relearning_steps, is_system)
    VALUES (NULL, 'Second System', 90, ARRAY['1m'], ARRAY['10m'], true)
  $$,
  '23505',
  NULL,
  'one_system_review_pacing_preset rejects a second is_system = true row'
);

-- Alice: one custom preset. IDs are given explicitly (the id column is
-- GENERATED BY DEFAULT, not ALWAYS, so an explicit value is allowed) so the
-- rest of this file can reference them directly instead of round-tripping
-- through a psql variable across role switches.
SELECT tests.set_claims('a1111111-1111-1111-1111-111111111111'::uuid);
SET LOCAL role = 'authenticated';

INSERT INTO public.review_pacing_presets (id, name, desired_retention, learning_steps, relearning_steps)
VALUES (9001, 'Alice Custom', 95, ARRAY['1m'], ARRAY['1d']);

-- Bob: one private preset.
SET LOCAL role = 'postgres';
SELECT tests.set_claims('b2222222-2222-2222-2222-222222222222'::uuid);
SET LOCAL role = 'authenticated';

INSERT INTO public.review_pacing_presets (id, name, desired_retention, learning_steps, relearning_steps)
VALUES (9002, 'Bob Private', 80, ARRAY['5m'], ARRAY['5m']);


-- ── Act as Alice — RLS SELECT ─────────────────────────────────────────────────

SET LOCAL role = 'postgres';
SELECT tests.set_claims('a1111111-1111-1111-1111-111111111111'::uuid);
SET LOCAL role = 'authenticated';

-- Test 3: Alice can select the system preset.
SELECT ok(
  EXISTS(SELECT 1 FROM public.review_pacing_presets WHERE is_system),
  'Alice can select the system preset'
);

-- Test 4: Alice can select her own preset.
SELECT ok(
  EXISTS(SELECT 1 FROM public.review_pacing_presets WHERE id = 9001),
  'Alice can select her own preset'
);

-- Test 5: Alice cannot select Bob's private preset.
SELECT is(
  (SELECT count(*)::int FROM public.review_pacing_presets WHERE id = 9002),
  0,
  'Alice cannot select Bob''s private preset'
);


-- ── Act as Alice — RLS INSERT/UPDATE/DELETE on the system preset ─────────────

-- Test 6: Alice cannot insert a preset with is_system = true for herself.
SELECT throws_ok(
  $$
    INSERT INTO public.review_pacing_presets
      (name, desired_retention, learning_steps, relearning_steps, is_system)
    VALUES ('Sneaky', 90, ARRAY['1m'], ARRAY['10m'], true)
  $$,
  '42501',
  NULL,
  'Alice cannot self-grant is_system = true on insert'
);

-- Test 7: Alice's attempt to rename the system preset silently affects 0 rows
-- (USING excludes is_system rows, so RLS no-ops the UPDATE rather than
-- throwing) — the system preset's name is untouched.
UPDATE public.review_pacing_presets SET name = 'Hacked' WHERE is_system;
SELECT is(
  (SELECT name FROM public.review_pacing_presets WHERE is_system),
  'Recommended',
  'Alice cannot rename the system preset'
);

-- Test 8: Alice's attempt to delete the system preset affects 0 rows — it
-- still exists afterward.
DELETE FROM public.review_pacing_presets WHERE is_system;
SELECT is(
  (SELECT count(*)::int FROM public.review_pacing_presets WHERE is_system),
  1,
  'Alice cannot delete the system preset'
);


-- ── decks_with_stats resolution ladder ────────────────────────────────────────

-- Deck 300: no preset, no overrides -> every field resolves to the system preset.
INSERT INTO public.decks (id, title, is_public) VALUES (300, 'No preset, no override', false);

-- Deck 301: preset assigned, no overrides -> every field resolves to the preset.
INSERT INTO public.decks (id, title, is_public, review_pacing_preset_id)
VALUES (301, 'Preset only', false, 9001);

-- Deck 302: preset assigned + desired_retention overridden only -> retention
-- resolves to the override, learning/relearning fall through to the preset.
INSERT INTO public.decks (id, title, is_public, review_pacing_preset_id, desired_retention_override)
VALUES (302, 'Mixed: retention overridden, rest from preset', false, 9001, 99);

-- Deck 303: no preset, learning/relearning overridden, retention not ->
-- retention falls all the way through to the system preset while
-- learning/relearning resolve to their overrides.
INSERT INTO public.decks (id, title, is_public, learning_steps_override, relearning_steps_override)
VALUES (303, 'Mixed: steps overridden, retention from system', false, ARRAY['30m'], ARRAY['1h']);

-- Test 9: deck 300 desired_retention resolves to the system value (tier 3).
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 300),
  90,
  'deck 300 desired_retention resolves to the system preset (no preset, no override)'
);

-- Test 10: deck 300 learning_steps resolves to the system value (tier 3).
SELECT is(
  (SELECT learning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 300),
  ARRAY['1m', '10m'],
  'deck 300 learning_steps resolves to the system preset'
);

-- Test 11: deck 300 relearning_steps resolves to the system value (tier 3).
SELECT is(
  (SELECT relearning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 300),
  ARRAY['10m'],
  'deck 300 relearning_steps resolves to the system preset'
);

-- Test 12: deck 300's raw override columns are all NULL.
SELECT is(
  (SELECT desired_retention_override FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 300),
  NULL::int,
  'deck 300 raw desired_retention_override is NULL'
);

-- Test 13: deck 301 desired_retention resolves to the linked preset (tier 2).
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 301),
  95,
  'deck 301 desired_retention resolves to the linked preset'
);

-- Test 14: deck 301 learning_steps resolves to the linked preset (tier 2).
SELECT is(
  (SELECT learning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 301),
  ARRAY['1m'],
  'deck 301 learning_steps resolves to the linked preset'
);

-- Test 15: deck 301 relearning_steps resolves to the linked preset (tier 2).
SELECT is(
  (SELECT relearning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 301),
  ARRAY['1d'],
  'deck 301 relearning_steps resolves to the linked preset'
);

-- Test 16: deck 302 desired_retention resolves to its own override (tier 1),
-- winning over the linked preset's value (95).
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 302),
  99,
  'deck 302 desired_retention resolves to its override, not the linked preset'
);

-- Test 17: deck 302 learning_steps (not overridden) falls through to the
-- linked preset — proves per-field resolution, not per-deck.
SELECT is(
  (SELECT learning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 302),
  ARRAY['1m'],
  'deck 302 learning_steps (unoverridden) still resolves to the linked preset'
);

-- Test 18: deck 302's raw desired_retention_override surfaces the actual
-- value, independent of the resolved column.
SELECT is(
  (SELECT desired_retention_override FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 302),
  99,
  'deck 302 raw desired_retention_override surfaces the actual override value'
);

-- Test 19: deck 302's raw learning_steps_override is NULL (only retention
-- was overridden).
SELECT is(
  (SELECT learning_steps_override FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 302),
  NULL::text[],
  'deck 302 raw learning_steps_override is NULL'
);

-- Test 19b: deck 302's raw relearning_steps_override is likewise NULL.
SELECT is(
  (SELECT relearning_steps_override FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 302),
  NULL::text[],
  'deck 302 raw relearning_steps_override is NULL'
);

-- Test 20: deck 303 desired_retention (no override, no preset) resolves to
-- the system value.
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 303),
  90,
  'deck 303 desired_retention resolves to the system preset (no override, no preset)'
);

-- Test 21: deck 303 learning_steps resolves to its own override (tier 1),
-- skipping straight past the (absent) preset tier to the override.
SELECT is(
  (SELECT learning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 303),
  ARRAY['30m'],
  'deck 303 learning_steps resolves to its override'
);

-- Test 22: deck 303 relearning_steps resolves to its own override (tier 1).
SELECT is(
  (SELECT relearning_steps FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 303),
  ARRAY['1h'],
  'deck 303 relearning_steps resolves to its override'
);


-- ── Deleting a custom preset SET NULLs the assigned deck's FK ────────────────

INSERT INTO public.review_pacing_presets (id, name, desired_retention, learning_steps, relearning_steps)
VALUES (9003, 'Alice Temp', 77, ARRAY['3m'], ARRAY['3d']);

INSERT INTO public.decks (id, title, is_public, review_pacing_preset_id)
VALUES (304, 'Delete-preset target', false, 9003);

-- Sanity check before delete.
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 304),
  77,
  'deck 304 resolves to the temp preset before it is deleted'
);

DELETE FROM public.review_pacing_presets WHERE id = 9003;

-- Test 23: deleting the preset SET NULLs the deck's FK (not cascade-deleted —
-- the deck row itself still exists — and not an error).
SELECT is(
  (SELECT review_pacing_preset_id FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 304),
  NULL::bigint,
  'deleting the assigned preset SET NULLs the deck FK'
);

-- Test 23b: the deck resolves back to the system preset's values.
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 304),
  90,
  'after the preset is deleted, the deck resolves back to the system preset'
);


-- ── Cross-member preset assignment does not leak private preset data ────────

SET LOCAL role = 'postgres';

-- A deck owned by Alice, pointed (by a superuser, bypassing any FE-level
-- guard) at Bob's private preset — there is no ownership check on the FK
-- itself, so this insert succeeds structurally.
INSERT INTO public.decks (id, member_id, title, is_public, review_pacing_preset_id)
VALUES (305, 'a1111111-1111-1111-1111-111111111111', 'Cross-member assignment', false, 9002);

SELECT tests.set_claims('a1111111-1111-1111-1111-111111111111'::uuid);
SET LOCAL role = 'authenticated';

-- Test 24: Alice's deck resolves to the system preset, NOT Bob's private
-- values (80) — RLS on review_pacing_presets blocks the LEFT JOIN from
-- seeing Bob's row under security_invoker, so COALESCE falls through.
SELECT is(
  (SELECT desired_retention FROM public.decks_with_stats(date_trunc('day', now())) WHERE id = 305),
  90,
  'a deck pointed at another member''s private preset does not leak its values — falls back to system'
);

SELECT * FROM finish();
ROLLBACK;
