-- =============================================================================
-- review_pacing_presets + get_member_decks review-pacing resolution
-- Rewritten for 20260717214625_collapse-pacing-overrides-into-jsonb.sql — the
-- old per-field `*_override` / `has_*_override` columns on deck_review_pacing
-- collapsed into a single `overrides` jsonb bag; key presence = pinned,
-- absence = follow the linked preset (or the system preset if none linked).
--
-- Covers:
--   1. one_system_review_pacing_preset partial unique index — only one
--      is_system = true row can ever exist.
--   2. RLS SELECT — a member sees the system preset + their own presets,
--      never another member's private preset.
--   3. RLS INSERT/UPDATE/DELETE — the system preset can never be edited,
--      deleted, or self-granted via is_system = true on insert.
--   4. get_member_decks resolution ladder — override -> preset -> system,
--      resolved independently per field (desired_retention, learning_steps,
--      relearning_steps), including a deck with fields split across tiers.
--   5. [obligation] empty overrides bag + a linked preset resolves every
--      field to the preset's values; no preset linked resolves to system
--      defaults.
--   6. Deleting a custom preset assigned to a deck SET NULLs the deck's FK
--      (not cascade, not error) and the deck resolves back to the system
--      preset's values.
--   7. Assigning another member's private preset to a deck does not leak
--      that member's preset values through get_member_decks.
--   8. Daily-limit resolution ladder distinguishes "no preset linked" from
--      "preset linked but its own max_reviews_per_day/max_new_per_day is
--      NULL" (that preset's explicit "unbounded") — a naive COALESCE would
--      wrongly fall through to the system default in the second case.
--   9. [obligation] a pinned-null max_interval override wins over a linked
--      preset's own numeric cap — resolves to NULL (uncapped), the FE lens's
--      "pinned-null" semantics encoded server-side.
--  10. deck_review_pacing RLS — a member cannot read or write another
--      member's deck_review_pacing row (SELECT and UPDATE/INSERT).
-- =============================================================================

BEGIN;

SELECT plan(32);

-- ── Setup (as postgres superuser) ─────────────────────────────────────────────

SELECT tests.create_user('a1111111-1111-1111-1111-111111111111'::uuid, 'alice_pacing');
SELECT tests.create_user('b2222222-2222-2222-2222-222222222222'::uuid, 'bob_pacing');

-- Test 1: the system preset seeded by the migration exists and is unique.
SELECT is(
  (SELECT count(*)::int FROM public.review_pacing_presets WHERE is_system),
  1,
  'exactly one system preset exists after the seed migration'
);

-- Test 2: the partial unique index rejects a second is_system = true row.
SELECT throws_ok(
  $$
    INSERT INTO public.review_pacing_presets
      (member_id, name, desired_retention, learning_steps, relearning_steps, is_system)
    VALUES (NULL, 'Second System', 90, ARRAY['1m'], ARRAY['10m'], true)
  $$,
  '23505',
  NULL,
  'one_system_review_pacing_preset rejects a second is_system = true row'
);

-- Alice: one custom preset. IDs are given explicitly (the id column is
-- GENERATED BY DEFAULT, not ALWAYS, so an explicit value is allowed) so the
-- rest of this file can reference them directly instead of round-tripping
-- through a psql variable across role switches.
SELECT tests.set_claims('a1111111-1111-1111-1111-111111111111'::uuid);
SET LOCAL role = 'authenticated';

INSERT INTO public.review_pacing_presets (id, name, desired_retention, learning_steps, relearning_steps)
VALUES (9001, 'Alice Custom', 95, ARRAY['1m'], ARRAY['1d']);

-- A second custom preset with an explicit max_reviews_per_day and max_interval,
-- and a NULL max_new_per_day (this preset's own "unbounded" for new cards) —
-- used by the daily-limit and pinned-null resolution-ladder tests below.
INSERT INTO public.review_pacing_presets
  (id, name, desired_retention, learning_steps, relearning_steps, max_reviews_per_day, max_new_per_day, max_interval)
VALUES (9004, 'Alice Capped', 92, ARRAY['1m'], ARRAY['1d'], 40, NULL, 60);

-- Bob: one private preset.
SET LOCAL role = 'postgres';
SELECT tests.set_claims('b2222222-2222-2222-2222-222222222222'::uuid);
SET LOCAL role = 'authenticated';

INSERT INTO public.review_pacing_presets (id, name, desired_retention, learning_steps, relearning_steps)
VALUES (9002, 'Bob Private', 80, ARRAY['5m'], ARRAY['5m']);


-- ── Act as Alice — RLS SELECT ─────────────────────────────────────────────────

SET LOCAL role = 'postgres';
SELECT tests.set_claims('a1111111-1111-1111-1111-111111111111'::uuid);
SET LOCAL role = 'authenticated';

-- Test 3: Alice can select the system preset.
SELECT ok(
  EXISTS(SELECT 1 FROM public.review_pacing_presets WHERE is_system),
  'Alice can select the system preset'
);

-- Test 4: Alice can select her own preset.
SELECT ok(
  EXISTS(SELECT 1 FROM public.review_pacing_presets WHERE id = 9001),
  'Alice can select her own preset'
);

-- Test 5: Alice cannot select Bob's private preset.
SELECT is(
  (SELECT count(*)::int FROM public.review_pacing_presets WHERE id = 9002),
  0,
  'Alice cannot select Bob''s private preset'
);


-- ── Act as Alice — RLS INSERT/UPDATE/DELETE on the system preset ─────────────

-- Test 6: Alice cannot insert a preset with is_system = true for herself.
SELECT throws_ok(
  $$
    INSERT INTO public.review_pacing_presets
      (name, desired_retention, learning_steps, relearning_steps, is_system)
    VALUES ('Sneaky', 90, ARRAY['1m'], ARRAY['10m'], true)
  $$,
  '42501',
  NULL,
  'Alice cannot self-grant is_system = true on insert'
);

-- Test 7: Alice's attempt to rename the system preset silently affects 0 rows
-- (USING excludes is_system rows, so RLS no-ops the UPDATE rather than
-- throwing) — the system preset's name is untouched.
UPDATE public.review_pacing_presets SET name = 'Hacked' WHERE is_system;
SELECT is(
  (SELECT name FROM public.review_pacing_presets WHERE is_system),
  'Recommended',
  'Alice cannot rename the system preset'
);

-- Test 8: Alice's attempt to delete the system preset affects 0 rows — it
-- still exists afterward.
DELETE FROM public.review_pacing_presets WHERE is_system;
SELECT is(
  (SELECT count(*)::int FROM public.review_pacing_presets WHERE is_system),
  1,
  'Alice cannot delete the system preset'
);


-- ── get_member_decks resolution ladder ────────────────────────────────────────

-- Deck 300: no preset, no overrides -> every field resolves to the system preset.
INSERT INTO public.decks (id, title, is_public) VALUES (300, 'No preset, no override', false);

-- Deck 301 [obligation]: preset assigned, empty overrides bag -> every field
-- resolves to the preset's values.
INSERT INTO public.decks (id, title, is_public) VALUES (301, 'Preset only', false);
INSERT INTO public.deck_review_pacing (deck_id, review_pacing_preset_id) VALUES (301, 9001);

-- Deck 302: preset assigned + desired_retention pinned in overrides -> retention
-- resolves to the override, learning/relearning fall through to the preset.
INSERT INTO public.decks (id, title, is_public) VALUES (302, 'Mixed: retention overridden, rest from preset', false);
INSERT INTO public.deck_review_pacing (deck_id, review_pacing_preset_id, overrides)
VALUES (302, 9001, '{"desired_retention": 99}'::jsonb);

-- Deck 303: no preset, learning/relearning pinned, retention not ->
-- retention falls all the way through to the system preset while
-- learning/relearning resolve to their overrides.
INSERT INTO public.decks (id, title, is_public) VALUES (303, 'Mixed: steps overridden, retention from system', false);
INSERT INTO public.deck_review_pacing (deck_id, overrides)
VALUES (303, '{"learning_steps": ["30m"], "relearning_steps": ["1h"]}'::jsonb);

-- Test 9: deck 300 desired_retention resolves to the system value (tier 3).
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 300),
  90,
  'deck 300 desired_retention resolves to the system preset (no preset, no override)'
);

-- Test 10: deck 300 learning_steps resolves to the system value (tier 3).
SELECT is(
  (SELECT learning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 300),
  ARRAY['1m', '10m'],
  'deck 300 learning_steps resolves to the system preset'
);

-- Test 11: deck 300 relearning_steps resolves to the system value (tier 3).
SELECT is(
  (SELECT relearning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 300),
  ARRAY['10m'],
  'deck 300 relearning_steps resolves to the system preset'
);

-- Test 12 [obligation]: deck 301 (empty overrides bag, linked preset)
-- desired_retention resolves to the linked preset's value.
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 301),
  95,
  'deck 301 (empty overrides, linked preset) desired_retention resolves to the preset [obligation]'
);

-- Test 13 [obligation]: deck 301 learning_steps resolves to the linked preset.
SELECT is(
  (SELECT learning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 301),
  ARRAY['1m'],
  'deck 301 (empty overrides, linked preset) learning_steps resolves to the preset [obligation]'
);

-- Test 14 [obligation]: deck 301 relearning_steps resolves to the linked preset.
SELECT is(
  (SELECT relearning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 301),
  ARRAY['1d'],
  'deck 301 (empty overrides, linked preset) relearning_steps resolves to the preset [obligation]'
);

-- Test 15: deck 302 desired_retention resolves to its own override (tier 1),
-- winning over the linked preset's value (95).
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 302),
  99,
  'deck 302 desired_retention resolves to its override, not the linked preset'
);

-- Test 16: deck 302 learning_steps (not overridden) falls through to the
-- linked preset — proves per-field resolution, not per-deck.
SELECT is(
  (SELECT learning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 302),
  ARRAY['1m'],
  'deck 302 learning_steps (unoverridden) still resolves to the linked preset'
);

-- Test 17: deck 302's raw pacing_overrides bag surfaces the actual pinned
-- key/value, independent of the resolved column.
SELECT is(
  (SELECT pacing_overrides FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 302),
  '{"desired_retention": 99}'::jsonb,
  'deck 302 raw pacing_overrides surfaces the actual pinned key'
);

-- Test 18: deck 303 desired_retention (no override, no preset) resolves to
-- the system value.
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 303),
  90,
  'deck 303 desired_retention resolves to the system preset (no override, no preset)'
);

-- Test 19: deck 303 learning_steps resolves to its own override (tier 1),
-- skipping straight past the (absent) preset tier to the override.
SELECT is(
  (SELECT learning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 303),
  ARRAY['30m'],
  'deck 303 learning_steps resolves to its override'
);

-- Test 20: deck 303 relearning_steps resolves to its own override (tier 1).
SELECT is(
  (SELECT relearning_steps FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 303),
  ARRAY['1h'],
  'deck 303 relearning_steps resolves to its override'
);


-- ── Deleting a custom preset SET NULLs the assigned deck's FK ────────────────

INSERT INTO public.review_pacing_presets (id, name, desired_retention, learning_steps, relearning_steps)
VALUES (9003, 'Alice Temp', 77, ARRAY['3m'], ARRAY['3d']);

INSERT INTO public.decks (id, title, is_public) VALUES (304, 'Delete-preset target', false);
INSERT INTO public.deck_review_pacing (deck_id, review_pacing_preset_id) VALUES (304, 9003);

-- Sanity check before delete.
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 304),
  77,
  'deck 304 resolves to the temp preset before it is deleted'
);

DELETE FROM public.review_pacing_presets WHERE id = 9003;

-- Test 21: deleting the preset SET NULLs the deck's FK (not cascade-deleted —
-- the deck row itself still exists — and not an error).
SELECT is(
  (SELECT review_pacing_preset_id FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 304),
  NULL::bigint,
  'deleting the assigned preset SET NULLs the deck FK'
);

-- Test 22: the deck resolves back to the system preset's values.
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 304),
  90,
  'after the preset is deleted, the deck resolves back to the system preset'
);


-- ── Cross-member preset assignment does not leak private preset data ────────

SET LOCAL role = 'postgres';

-- A deck owned by Alice, pointed (by a superuser, bypassing any FE-level
-- guard) at Bob's private preset — there is no ownership check on the FK
-- itself, so this insert succeeds structurally.
INSERT INTO public.decks (id, member_id, title, is_public)
VALUES (305, 'a1111111-1111-1111-1111-111111111111', 'Cross-member assignment', false);
INSERT INTO public.deck_review_pacing (deck_id, review_pacing_preset_id) VALUES (305, 9002);

SELECT tests.set_claims('a1111111-1111-1111-1111-111111111111'::uuid);
SET LOCAL role = 'authenticated';

-- Test 23: Alice's deck resolves to the system preset, NOT Bob's private
-- values (80) — RLS on review_pacing_presets blocks the LEFT JOIN from
-- seeing Bob's row under security_invoker, so the ladder falls through.
SELECT is(
  (SELECT desired_retention FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 305),
  90,
  'a deck pointed at another member''s private preset does not leak its values — falls back to system'
);


-- ── Daily-limit resolution ladder [obligation] ────────────────────────────────
-- Distinguishes "no preset linked" (falls through to the system default)
-- from "preset linked but its own max_*_per_day is NULL" (that preset's
-- explicit "unbounded" — must NOT fall through to the system default).

-- Deck 306: no preset, no override -> system default.
INSERT INTO public.decks (id, title, is_public) VALUES (306, 'No preset - system default', false);

-- Deck 307: linked to preset 9004 (max_reviews_per_day = 40, max_new_per_day
-- = NULL, max_interval = 60). max_reviews_per_day must resolve to 40 (the
-- preset's value), and max_new_per_day must resolve to NULL (the preset's
-- own "unbounded") — NOT fall through to the system preset's value.
INSERT INTO public.decks (id, title, is_public) VALUES (307, 'Preset with NULL max_new_per_day', false);
INSERT INTO public.deck_review_pacing (deck_id, review_pacing_preset_id) VALUES (307, 9004);

-- Test 24: deck 306 (no preset linked) resolves max_reviews_per_day to the
-- system preset's value, proving the "no preset" branch still falls through.
SELECT is(
  (SELECT max_reviews_per_day FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 306),
  (SELECT max_reviews_per_day FROM public.review_pacing_presets WHERE is_system),
  'deck 306 (no preset) resolves max_reviews_per_day to the system preset [obligation]'
);

-- Test 25: deck 307 max_reviews_per_day resolves to the linked preset's
-- concrete value (40), not the system default.
SELECT is(
  (SELECT max_reviews_per_day FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 307),
  40,
  'deck 307 max_reviews_per_day resolves to the linked preset''s concrete cap [obligation]'
);

-- Test 26 [obligation]: deck 307 max_new_per_day resolves to NULL — the
-- linked preset's own "unbounded" — and must NOT fall through to the system
-- preset's max_new_per_day (a naive COALESCE would get this wrong).
SELECT is(
  (SELECT max_new_per_day FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 307),
  NULL::int,
  'deck 307 max_new_per_day resolves to the linked preset''s own NULL (unbounded), not the system default [obligation]'
);

-- Test 27 [obligation]: a pinned-null max_interval override wins over the
-- linked preset's own numeric cap (60) — key present with a null value
-- means "pinned to uncapped", resolving to NULL rather than the preset's
-- concrete value.
INSERT INTO public.decks (id, title, is_public) VALUES (308, 'Pinned-null max_interval over a capped preset', false);
INSERT INTO public.deck_review_pacing (deck_id, review_pacing_preset_id, overrides)
VALUES (308, 9004, '{"max_interval": null}'::jsonb);

SELECT is(
  (SELECT max_interval FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 308),
  NULL::int,
  'a pinned-null max_interval override resolves to NULL even when the linked preset has a numeric cap [obligation]'
);

-- Test 28: the same deck's max_reviews_per_day (not pinned) still resolves
-- to the linked preset's concrete value — proving the pin is scoped to the
-- one field, not the whole deck.
SELECT is(
  (SELECT max_reviews_per_day FROM public.get_member_decks(date_trunc('day', now())) WHERE id = 308),
  40,
  'deck 308 max_reviews_per_day (unpinned) still resolves to the linked preset'
);


-- ── deck_review_pacing RLS [obligation] ───────────────────────────────────────
-- deck_review_pacing has no member_id column of its own — ownership is
-- proved via EXISTS(decks d WHERE d.id = deck_id AND d.member_id = auth.uid()).

SET LOCAL role = 'postgres';
SELECT tests.set_claims('b2222222-2222-2222-2222-222222222222'::uuid);
SET LOCAL role = 'authenticated';

-- Test 29 [obligation]: Bob cannot SELECT Alice's deck_review_pacing row
-- (deck 301, owned by Alice).
SELECT is(
  (SELECT count(*)::int FROM public.deck_review_pacing WHERE deck_id = 301),
  0,
  'Bob cannot SELECT Alice''s deck_review_pacing row [obligation]'
);

-- Test 30 [obligation]: Bob's UPDATE against Alice's deck_review_pacing row
-- affects 0 rows (RLS USING excludes it — no error, just a no-op).
UPDATE public.deck_review_pacing SET overrides = '{"desired_retention": 60}'::jsonb WHERE deck_id = 301;
SET LOCAL role = 'postgres';
SELECT is(
  (SELECT overrides FROM public.deck_review_pacing WHERE deck_id = 301),
  '{}'::jsonb,
  'Bob cannot UPDATE Alice''s deck_review_pacing row [obligation]'
);

-- Test 31 [obligation]: Bob cannot INSERT a deck_review_pacing row for a
-- deck he does not own — WITH CHECK rejects it.
SELECT tests.set_claims('b2222222-2222-2222-2222-222222222222'::uuid);
SET LOCAL role = 'authenticated';
SELECT throws_ok(
  $$ INSERT INTO public.deck_review_pacing (deck_id, overrides) VALUES (300, '{"desired_retention": 55}'::jsonb) $$,
  '42501',
  NULL,
  'Bob cannot INSERT a deck_review_pacing row for a deck he does not own [obligation]'
);

SELECT * FROM finish();
ROLLBACK;
