-- Generated from pg_dump via scripts/dump-schemas; edit freely — this file is
-- the canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TABLE public.cards (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    front_text text,
    back_text text,
    deck_id bigint,
    member_id uuid,
    rank numeric(20,6) NOT NULL,
    note text
);


ALTER TABLE public.cards OWNER TO postgres;


CREATE TABLE public.lessons (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    audio_path text NOT NULL,
    transcript jsonb DEFAULT '{}'::jsonb NOT NULL,
    lang text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    collection_id bigint NOT NULL,
    status text DEFAULT 'ready'::text NOT NULL,
    error_code text,
    phase text,
    script text DEFAULT 'original'::text NOT NULL,
    "position" numeric NOT NULL,
    chunks jsonb DEFAULT '[]'::jsonb NOT NULL,
    chunk_cursor integer DEFAULT 0 NOT NULL,
    CONSTRAINT lessons_status_check CHECK ((status = ANY (ARRAY['processing'::text, 'ready'::text, 'failed'::text])))
);


ALTER TABLE public.lessons OWNER TO postgres;


CREATE TABLE public.media (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_id uuid,
    card_id bigint,
    deck_id bigint,
    bucket text NOT NULL,
    path text NOT NULL,
    deleted_at timestamp with time zone,
    slot public.media_slot,
    lesson_id bigint
);


ALTER TABLE public.media OWNER TO postgres;


CREATE TABLE public.feedback_items (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    body text,
    type public.feedback_type NOT NULL,
    status public.feedback_status DEFAULT 'new'::public.feedback_status NOT NULL,
    visibility public.feedback_visibility DEFAULT 'internal'::public.feedback_visibility NOT NULL
);


ALTER TABLE public.feedback_items OWNER TO postgres;


ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.decks (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    description text,
    is_public boolean DEFAULT false NOT NULL,
    title text,
    member_id uuid NOT NULL,
    tags text[],
    has_image boolean DEFAULT false,
    study_config jsonb,
    cover_config jsonb DEFAULT '{"icon": "symbol-spades", "theme": "blue-500", "pattern": "diagonal-stripes", "theme_dark": "blue-650"}'::jsonb,
    card_attributes jsonb,
    rank numeric NOT NULL
);


ALTER TABLE public.decks OWNER TO postgres;


ALTER TABLE public.decks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Decks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.deck_review_pacing (
    deck_id bigint NOT NULL,
    review_pacing_preset_id bigint,
    desired_retention_override integer,
    learning_steps_override text[],
    relearning_steps_override text[],
    has_max_reviews_override boolean DEFAULT false NOT NULL,
    max_reviews_per_day_override integer,
    has_max_new_override boolean DEFAULT false NOT NULL,
    max_new_per_day_override integer
);


ALTER TABLE public.deck_review_pacing OWNER TO postgres;


ALTER TABLE public.feedback_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.feedback_votes (
    feedback_id bigint NOT NULL,
    member_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.feedback_votes OWNER TO postgres;


CREATE TABLE public.shop_items (
    id bigint NOT NULL,
    name text,
    item_key text,
    description text,
    price smallint,
    category public.shop_category
);


ALTER TABLE public.shop_items OWNER TO postgres;


ALTER TABLE public.shop_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.lesson_collections (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_lesson_id bigint,
    last_position_seconds double precision DEFAULT 0 NOT NULL
);


ALTER TABLE public.lesson_collections OWNER TO postgres;


ALTER TABLE public.lesson_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.members (
    id uuid NOT NULL,
    display_name text NOT NULL,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    description text,
    avatar_url text,
    email text,
    role public.member_role DEFAULT 'user'::public.member_role NOT NULL,
    plan text DEFAULT 'free'::text NOT NULL,
    stripe_customer_id text,
    stripe_subscription_id text,
    preferences jsonb DEFAULT '{}'::jsonb NOT NULL,
    cover_config jsonb
);


ALTER TABLE public.members OWNER TO postgres;


CREATE TABLE public.plans (
    id text NOT NULL,
    stripe_price_id text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cards_per_deck_limit integer,
    deck_limit integer
);


ALTER TABLE public.plans OWNER TO postgres;


CREATE TABLE public.purchases (
    id bigint NOT NULL,
    member_id uuid,
    item_id bigint,
    quantity smallint
);


ALTER TABLE public.purchases OWNER TO postgres;


ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.review_logs (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    card_id bigint NOT NULL,
    member_id uuid NOT NULL,
    rating smallint NOT NULL,
    state smallint NOT NULL,
    due timestamp with time zone NOT NULL,
    stability real,
    difficulty real,
    scheduled_days smallint,
    review timestamp with time zone NOT NULL
);


ALTER TABLE public.review_logs OWNER TO postgres;


ALTER TABLE public.review_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.review_pacing_presets (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_id uuid,
    name text NOT NULL,
    desired_retention integer NOT NULL,
    learning_steps text[] NOT NULL,
    relearning_steps text[] NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    max_reviews_per_day integer,
    max_new_per_day integer
);


ALTER TABLE public.review_pacing_presets OWNER TO postgres;


ALTER TABLE public.review_pacing_presets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_pacing_presets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.reviews (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    card_id bigint,
    member_id uuid,
    difficulty real,
    due timestamp with time zone DEFAULT now(),
    elapsed_days smallint,
    lapses smallint,
    last_review date,
    learning_steps smallint,
    reps smallint,
    scheduled_days smallint,
    stability real,
    state smallint DEFAULT 2 NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;


ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT "Cards_pkey" PRIMARY KEY (id);


ALTER TABLE ONLY public.decks
    ADD CONSTRAINT "Decks_pkey" PRIMARY KEY (id);


ALTER TABLE ONLY public.members
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_id_key UNIQUE (id);


ALTER TABLE ONLY public.deck_review_pacing
    ADD CONSTRAINT deck_review_pacing_pkey PRIMARY KEY (deck_id);


ALTER TABLE ONLY public.decks
    ADD CONSTRAINT decks_id_key UNIQUE (id);


ALTER TABLE ONLY public.feedback_items
    ADD CONSTRAINT feedback_items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.feedback_votes
    ADD CONSTRAINT feedback_votes_pkey PRIMARY KEY (feedback_id, member_id);


ALTER TABLE ONLY public.shop_items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_display_name_key UNIQUE (display_name);


ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_stripe_customer_id_key UNIQUE (stripe_customer_id);


ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_stripe_price_id_key UNIQUE (stripe_price_id);


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.review_logs
    ADD CONSTRAINT review_logs_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.review_pacing_presets
    ADD CONSTRAINT review_pacing_presets_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT unique_member_item UNIQUE (member_id, item_id);


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT unique_review_per_user_card UNIQUE (card_id);


CREATE INDEX cards_deck_front_back_text_idx ON public.cards USING btree (deck_id, front_text, back_text);


CREATE INDEX cards_deck_id_idx ON public.cards USING hash (deck_id);


CREATE INDEX cards_deck_rank_idx ON public.cards USING btree (deck_id, rank);


CREATE INDEX cards_member_id_idx ON public.cards USING hash (member_id);


CREATE INDEX decks_id_is_public_idx ON public.decks USING btree (id, is_public);


CREATE INDEX decks_member_id_idx ON public.decks USING hash (member_id);


CREATE INDEX lesson_collections_member_id_created_at_idx ON public.lesson_collections USING btree (member_id, created_at DESC);


CREATE INDEX lessons_collection_id_position_idx ON public.lessons USING btree (collection_id, "position");


CREATE INDEX media_bucket_path_idx ON public.media USING btree (bucket, path);


CREATE UNIQUE INDEX media_card_slot_active_uniq ON public.media USING btree (card_id, slot) WHERE ((deleted_at IS NULL) AND (card_id IS NOT NULL));


CREATE INDEX media_card_slot_idx ON public.media USING btree (card_id, slot) WHERE (deleted_at IS NULL);


CREATE INDEX media_member_id_idx ON public.media USING btree (member_id) WHERE (deleted_at IS NULL);


CREATE UNIQUE INDEX one_system_review_pacing_preset ON public.review_pacing_presets USING btree (is_system) WHERE is_system;


CREATE INDEX purchases_member_id_idx ON public.purchases USING btree (member_id);


CREATE INDEX review_logs_card_id_idx ON public.review_logs USING btree (card_id);


CREATE INDEX review_logs_member_id_idx ON public.review_logs USING btree (member_id, review DESC);


CREATE INDEX reviews_card_id_due_member_id_idx ON public.reviews USING btree (card_id, due, member_id);


ALTER TABLE ONLY public.members
    ADD CONSTRAINT "Users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.deck_review_pacing
    ADD CONSTRAINT deck_review_pacing_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.deck_review_pacing
    ADD CONSTRAINT deck_review_pacing_review_pacing_preset_id_fkey FOREIGN KEY (review_pacing_preset_id) REFERENCES public.review_pacing_presets(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.decks
    ADD CONSTRAINT decks_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.feedback_items
    ADD CONSTRAINT feedback_items_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.feedback_votes
    ADD CONSTRAINT feedback_votes_feedback_id_fkey FOREIGN KEY (feedback_id) REFERENCES public.feedback_items(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.feedback_votes
    ADD CONSTRAINT feedback_votes_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_last_lesson_id_fkey FOREIGN KEY (last_lesson_id) REFERENCES public.lessons(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.lesson_collections(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id);


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(id);


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_plan_fkey FOREIGN KEY (plan) REFERENCES public.plans(id);


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.shop_items(id) ON UPDATE RESTRICT;


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE RESTRICT ON DELETE CASCADE;


ALTER TABLE ONLY public.review_logs
    ADD CONSTRAINT review_logs_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.review_logs
    ADD CONSTRAINT review_logs_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.review_pacing_presets
    ADD CONSTRAINT review_pacing_presets_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;

