-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TYPE public.media_slot AS ENUM (
    'card_front',
    'card_back'
);


ALTER TYPE public.media_slot OWNER TO postgres;


CREATE TABLE public.media (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_id uuid,
    card_id bigint,
    deck_id bigint,
    bucket text NOT NULL,
    path text NOT NULL,
    deleted_at timestamp with time zone,
    slot public.media_slot,
    lesson_id bigint
);


ALTER TABLE public.media OWNER TO postgres;


ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id);


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(id);


CREATE INDEX media_bucket_path_idx ON public.media USING btree (bucket, path);


CREATE UNIQUE INDEX media_card_slot_active_uniq ON public.media USING btree (card_id, slot) WHERE ((deleted_at IS NULL) AND (card_id IS NOT NULL));


CREATE INDEX media_card_slot_idx ON public.media USING btree (card_id, slot) WHERE (deleted_at IS NULL);


CREATE INDEX media_member_id_idx ON public.media USING btree (member_id) WHERE (deleted_at IS NULL);


CREATE VIEW public.cards_with_images WITH (security_invoker='true') AS
 SELECT c.id,
    c.created_at,
    c.updated_at,
    c.front_text,
    c.back_text,
    c.deck_id,
    c.member_id,
    c.rank,
    front.bucket AS front_image_bucket,
    front.path AS front_image_path,
    back.bucket AS back_image_bucket,
    back.path AS back_image_path,
    ((c.front_text <> ''::text) AND (c.back_text <> ''::text) AND (count(*) OVER (PARTITION BY c.deck_id, c.front_text, c.back_text) > 1)) AS is_duplicate
   FROM ((public.cards c
     LEFT JOIN public.media front ON (((front.card_id = c.id) AND (front.slot = 'card_front'::public.media_slot) AND (front.deleted_at IS NULL))))
     LEFT JOIN public.media back ON (((back.card_id = c.id) AND (back.slot = 'card_back'::public.media_slot) AND (back.deleted_at IS NULL))));


ALTER TABLE public.cards_with_images OWNER TO postgres;


CREATE FUNCTION public.dedupe_media_slot_on_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF NEW.card_id IS NOT NULL AND NEW.slot IS NOT NULL THEN
    UPDATE public.media
    SET deleted_at = now()
    WHERE card_id = NEW.card_id
      AND slot = NEW.slot
      AND deleted_at IS NULL;
  END IF;

  RETURN NEW;
END;
$$;


ALTER FUNCTION public.dedupe_media_slot_on_insert() OWNER TO postgres;


GRANT ALL ON FUNCTION public.dedupe_media_slot_on_insert() TO anon;
GRANT ALL ON FUNCTION public.dedupe_media_slot_on_insert() TO authenticated;
GRANT ALL ON FUNCTION public.dedupe_media_slot_on_insert() TO service_role;


CREATE FUNCTION public.find_orphan_storage_objects(p_older_than interval DEFAULT '01:00:00'::interval, p_limit integer DEFAULT 500) RETURNS TABLE(bucket text, name text)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public', 'storage'
    AS $$
  SELECT o.bucket_id, o.name
  FROM storage.objects o
  WHERE o.bucket_id IN (SELECT DISTINCT m.bucket FROM public.media m)
    AND o.created_at < now() - p_older_than
    AND NOT EXISTS (
      SELECT 1
      FROM public.media m
      WHERE m.bucket = o.bucket_id
        AND m.path = o.name
    )
  LIMIT p_limit;
$$;


ALTER FUNCTION public.find_orphan_storage_objects(p_older_than interval, p_limit integer) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.find_orphan_storage_objects(p_older_than interval, p_limit integer) FROM PUBLIC;
GRANT ALL ON FUNCTION public.find_orphan_storage_objects(p_older_than interval, p_limit integer) TO service_role;


CREATE FUNCTION public.invoke_cleanup_media() RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
DECLARE
  v_url         text;
  v_service_key text;
BEGIN
  SELECT decrypted_secret INTO v_url
  FROM vault.decrypted_secrets
  WHERE name = 'supabase_url'
  LIMIT 1;

  IF v_url IS NULL THEN
    RAISE EXCEPTION
      'Vault secret "supabase_url" not found. '
      'Run: SELECT vault.create_secret(''<url>'', ''supabase_url'');';
  END IF;

  SELECT decrypted_secret INTO v_service_key
  FROM vault.decrypted_secrets
  WHERE name = 'service_role_key'
  LIMIT 1;

  IF v_service_key IS NULL THEN
    RAISE EXCEPTION
      'Vault secret "service_role_key" not found. '
      'Run: SELECT vault.create_secret(''<key>'', ''service_role_key'');';
  END IF;

  PERFORM net.http_post(
    url     := v_url || '/functions/v1/cleanup-media',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || v_service_key,
      'Content-Type',  'application/json'
    ),
    body    := '{}'::jsonb
  );
END;
$$;


ALTER FUNCTION public.invoke_cleanup_media() OWNER TO postgres;


-- Owner-only: the hourly pg_cron job runs as postgres (the owner), which
-- always retains EXECUTE. Nobody else may trigger the sweep. Crucially this
-- keeps the function off PostgREST's RPC surface — a grant to anon/authenticated
-- would expose POST /rest/v1/rpc/invoke_cleanup_media, and since the function is
-- SECURITY DEFINER it would fire the edge function with the Vault service_role
-- key, sailing past the edge function's own caller-auth gate.
REVOKE ALL ON FUNCTION public.invoke_cleanup_media() FROM PUBLIC;


CREATE FUNCTION public.soft_delete_media_before_card_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  UPDATE public.media
  SET
    deleted_at = COALESCE(deleted_at, now()),
    card_id    = NULL
  WHERE card_id = OLD.id;

  RETURN OLD;
END;
$$;


ALTER FUNCTION public.soft_delete_media_before_card_delete() OWNER TO postgres;


GRANT ALL ON FUNCTION public.soft_delete_media_before_card_delete() TO anon;
GRANT ALL ON FUNCTION public.soft_delete_media_before_card_delete() TO authenticated;
GRANT ALL ON FUNCTION public.soft_delete_media_before_card_delete() TO service_role;


CREATE FUNCTION public.soft_delete_media_before_deck_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  UPDATE public.media
  SET
    deleted_at = COALESCE(deleted_at, now()),
    deck_id    = NULL
  WHERE deck_id = OLD.id;

  RETURN OLD;
END;
$$;


ALTER FUNCTION public.soft_delete_media_before_deck_delete() OWNER TO postgres;


GRANT ALL ON FUNCTION public.soft_delete_media_before_deck_delete() TO anon;
GRANT ALL ON FUNCTION public.soft_delete_media_before_deck_delete() TO authenticated;
GRANT ALL ON FUNCTION public.soft_delete_media_before_deck_delete() TO service_role;


CREATE FUNCTION public.soft_delete_media_before_lesson_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  UPDATE public.media
  SET
    deleted_at = COALESCE(deleted_at, now()),
    lesson_id  = NULL
  WHERE lesson_id = OLD.id;

  RETURN OLD;
END;
$$;


ALTER FUNCTION public.soft_delete_media_before_lesson_delete() OWNER TO postgres;


GRANT ALL ON FUNCTION public.soft_delete_media_before_lesson_delete() TO anon;
GRANT ALL ON FUNCTION public.soft_delete_media_before_lesson_delete() TO authenticated;
GRANT ALL ON FUNCTION public.soft_delete_media_before_lesson_delete() TO service_role;


CREATE FUNCTION public.soft_delete_media_before_member_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  UPDATE public.media
  SET deleted_at = now()
  WHERE member_id = OLD.id
    AND deleted_at IS NULL;

  RETURN OLD;
END;
$$;


ALTER FUNCTION public.soft_delete_media_before_member_delete() OWNER TO postgres;


GRANT ALL ON FUNCTION public.soft_delete_media_before_member_delete() TO anon;
GRANT ALL ON FUNCTION public.soft_delete_media_before_member_delete() TO authenticated;
GRANT ALL ON FUNCTION public.soft_delete_media_before_member_delete() TO service_role;


CREATE TRIGGER set_member_id_on_media BEFORE INSERT ON public.media FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER trg_card_delete_soft_delete_media BEFORE DELETE ON public.cards FOR EACH ROW EXECUTE FUNCTION public.soft_delete_media_before_card_delete();


CREATE TRIGGER trg_deck_delete_soft_delete_media BEFORE DELETE ON public.decks FOR EACH ROW EXECUTE FUNCTION public.soft_delete_media_before_deck_delete();


CREATE TRIGGER trg_media_dedupe_slot BEFORE INSERT ON public.media FOR EACH ROW EXECUTE FUNCTION public.dedupe_media_slot_on_insert();


CREATE TRIGGER trg_member_delete_soft_delete_media BEFORE DELETE ON public.members FOR EACH ROW EXECUTE FUNCTION public.soft_delete_media_before_member_delete();


ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable delete for users based on user_id" ON public.media FOR DELETE USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "Enable insert for authenticated users only" ON public.media FOR INSERT TO authenticated WITH CHECK (((auth.uid() = member_id) AND ((NOT COALESCE((slot = ANY (ARRAY['card_front'::public.media_slot, 'card_back'::public.media_slot])), false)) OR (public.auth_plan() = 'paid'::text))));


CREATE POLICY "Enable update for users with member_id" ON public.media FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "Read own media or media in public decks" ON public.media FOR SELECT USING (((auth.uid() = member_id) OR (EXISTS ( SELECT 1
   FROM (public.cards c
     JOIN public.decks d ON ((d.id = c.deck_id)))
  WHERE ((c.id = media.card_id) AND (d.is_public = true)))) OR (EXISTS ( SELECT 1
   FROM public.decks d
  WHERE ((d.id = media.deck_id) AND (d.is_public = true))))));


GRANT ALL ON TABLE public.media TO anon;
GRANT ALL ON TABLE public.media TO authenticated;
GRANT ALL ON TABLE public.media TO service_role;


GRANT ALL ON TABLE public.cards_with_images TO anon;
GRANT ALL ON TABLE public.cards_with_images TO authenticated;
GRANT ALL ON TABLE public.cards_with_images TO service_role;


GRANT ALL ON SEQUENCE public.media_id_seq TO anon;
GRANT ALL ON SEQUENCE public.media_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.media_id_seq TO service_role;
