-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    audio_path text NOT NULL,
    lang text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    collection_id bigint NOT NULL,
    status text DEFAULT 'ready'::text NOT NULL,
    error_code text,
    phase text,
    script text DEFAULT 'original'::text NOT NULL,
    "position" numeric NOT NULL,
    chunks jsonb DEFAULT '[]'::jsonb NOT NULL,
    chunk_cursor integer DEFAULT 0 NOT NULL,
    CONSTRAINT lessons_status_check CHECK ((status = ANY (ARRAY['processing'::text, 'ready'::text, 'failed'::text])))
);


ALTER TABLE public.lessons OWNER TO postgres;


-- One row per transcript sentence, replacing the single accumulating transcript
-- blob. Each phase writes only its own columns: transcription seeds ordinal /
-- timing / text / words / paragraph_gap, chaptering stamps chapter_title on the
-- sentence a chapter opens on, paragraphing fills break_strength, translating
-- fills translation, transliterating fills readings (one entry per word,
-- index-aligned to `words`).
CREATE TABLE public.lesson_sentences (
    lesson_id bigint NOT NULL,
    ordinal integer NOT NULL,
    start_seconds double precision NOT NULL,
    end_seconds double precision NOT NULL,
    text text NOT NULL,
    words jsonb DEFAULT '[]'::jsonb NOT NULL,
    -- Silent seconds before this sentence, from the audio timing. 0 on the first.
    paragraph_gap double precision DEFAULT 0 NOT NULL,
    -- How strongly a paragraph break belongs before this sentence, 0–1, scored by
    -- meaning in the paragraphing phase. Null where that pass couldn't score it.
    break_strength double precision,
    translation text,
    readings jsonb,
    chapter_title text
);


ALTER TABLE public.lesson_sentences OWNER TO postgres;


CREATE TABLE public.lesson_collections (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_lesson_id bigint,
    last_position_seconds double precision DEFAULT 0 NOT NULL
);


ALTER TABLE public.lesson_collections OWNER TO postgres;


ALTER TABLE public.lesson_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.lesson_sentences
    ADD CONSTRAINT lesson_sentences_pkey PRIMARY KEY (lesson_id, ordinal);


ALTER TABLE ONLY public.lesson_sentences
    ADD CONSTRAINT lesson_sentences_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_last_lesson_id_fkey FOREIGN KEY (last_lesson_id) REFERENCES public.lessons(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.lesson_collections(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


CREATE INDEX lesson_collections_member_id_created_at_idx ON public.lesson_collections USING btree (member_id, created_at DESC);


CREATE INDEX lessons_collection_id_position_idx ON public.lessons USING btree (collection_id, "position");


CREATE VIEW public.lesson_collections_with_counts WITH (security_invoker='true') AS
 SELECT lc.id,
    lc.member_id,
    lc.title,
    lc.last_lesson_id,
    lc.last_position_seconds,
    lc.created_at,
    lc.updated_at,
    ( SELECT (count(*))::integer AS count
           FROM public.lessons l
          WHERE (l.collection_id = lc.id)) AS lesson_count
   FROM public.lesson_collections lc;


ALTER TABLE public.lesson_collections_with_counts OWNER TO postgres;


CREATE FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text DEFAULT 'original'::text, p_chunks jsonb DEFAULT '[]'::jsonb) RETURNS public.lessons
    LANGUAGE plpgsql
    AS $$
declare
  v_lesson public.lessons;
  v_position numeric;
  v_chunks jsonb;
begin
  -- Server-assigned chapter order within the collection (max + 1), same as cards.
  select coalesce(max("position"), 0) + 1
  into v_position
  from public.lessons
  where collection_id = p_collection_id;

  -- Empty manifest -> one chunk covering the whole file from offset 0.
  if p_chunks is null or jsonb_array_length(p_chunks) = 0 then
    v_chunks := jsonb_build_array(
      jsonb_build_object('path', p_audio_path, 'offset', 0)
    );
  else
    v_chunks := p_chunks;
  end if;

  insert into public.lessons
    (collection_id, title, audio_path,
     status, phase, script, "position", chunks, chunk_cursor)
  values
    (p_collection_id, p_title, p_audio_path,
     'processing', 'transcribing', p_script, v_position, v_chunks, 0)
  returning * into v_lesson;

  insert into public.media (bucket, path, lesson_id)
  values ('audio-lessons', p_audio_path, v_lesson.id);

  return v_lesson;
end;
$$;


ALTER FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_chunks jsonb) OWNER TO postgres;


GRANT ALL ON FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_chunks jsonb) TO anon;
GRANT ALL ON FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_chunks jsonb) TO authenticated;
GRANT ALL ON FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_chunks jsonb) TO service_role;


-- Transcription's per-chunk write: seed (or re-seed, on a duplicate delivery) the
-- sentence rows a chunk produced. Idempotent by (lesson_id, ordinal) — a replayed
-- chunk overwrites the same rows with the same values rather than duplicating.
CREATE FUNCTION public.upsert_lesson_sentences(p_lesson_id bigint, p_sentences jsonb) RETURNS void
    LANGUAGE sql
    AS $$
  insert into public.lesson_sentences
    (lesson_id, ordinal, start_seconds, end_seconds, text, words, paragraph_gap)
  select
    p_lesson_id, s.ordinal, s.start_seconds, s.end_seconds, s.text, s.words, s.paragraph_gap
  from jsonb_to_recordset(p_sentences) as s(
    ordinal integer, start_seconds double precision, end_seconds double precision,
    text text, words jsonb, paragraph_gap double precision
  )
  on conflict (lesson_id, ordinal) do update set
    start_seconds = excluded.start_seconds,
    end_seconds   = excluded.end_seconds,
    text          = excluded.text,
    words         = excluded.words,
    paragraph_gap = excluded.paragraph_gap;
$$;


ALTER FUNCTION public.upsert_lesson_sentences(p_lesson_id bigint, p_sentences jsonb) OWNER TO postgres;


-- Only the service-role worker writes sentence rows; a member never calls these
-- (see 20260807180000_lock-down-lesson-cron-functions for the same lockdown shape).
REVOKE ALL ON FUNCTION public.upsert_lesson_sentences(p_lesson_id bigint, p_sentences jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.upsert_lesson_sentences(p_lesson_id bigint, p_sentences jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.upsert_lesson_sentences(p_lesson_id bigint, p_sentences jsonb) FROM authenticated;
GRANT ALL ON FUNCTION public.upsert_lesson_sentences(p_lesson_id bigint, p_sentences jsonb) TO service_role;


-- Chaptering's write: clear every existing chapter mark, then stamp chapter_title
-- on each sentence a chapter opens on. Idempotent — a re-run reproduces the set.
CREATE FUNCTION public.set_lesson_chapters(p_lesson_id bigint, p_chapters jsonb) RETURNS void
    LANGUAGE plpgsql
    AS $$
begin
  update public.lesson_sentences
     set chapter_title = null
   where lesson_id = p_lesson_id and chapter_title is not null;

  update public.lesson_sentences ls
     set chapter_title = c.title
    from jsonb_to_recordset(p_chapters) as c(ordinal integer, title text)
   where ls.lesson_id = p_lesson_id and ls.ordinal = c.ordinal;
end;
$$;


ALTER FUNCTION public.set_lesson_chapters(p_lesson_id bigint, p_chapters jsonb) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.set_lesson_chapters(p_lesson_id bigint, p_chapters jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_lesson_chapters(p_lesson_id bigint, p_chapters jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.set_lesson_chapters(p_lesson_id bigint, p_chapters jsonb) FROM authenticated;
GRANT ALL ON FUNCTION public.set_lesson_chapters(p_lesson_id bigint, p_chapters jsonb) TO service_role;


-- Paragraphing's write: fill break_strength on a slice of sentences, keyed by
-- ordinal. Touches only the break_strength column, leaving every other field
-- intact; a sentence the pass couldn't score is simply absent from p_strengths.
CREATE FUNCTION public.set_lesson_break_strengths(p_lesson_id bigint, p_strengths jsonb) RETURNS void
    LANGUAGE sql
    AS $$
  update public.lesson_sentences ls
     set break_strength = s.strength
    from jsonb_to_recordset(p_strengths) as s(ordinal integer, strength double precision)
   where ls.lesson_id = p_lesson_id and ls.ordinal = s.ordinal;
$$;


ALTER FUNCTION public.set_lesson_break_strengths(p_lesson_id bigint, p_strengths jsonb) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.set_lesson_break_strengths(p_lesson_id bigint, p_strengths jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_lesson_break_strengths(p_lesson_id bigint, p_strengths jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.set_lesson_break_strengths(p_lesson_id bigint, p_strengths jsonb) FROM authenticated;
GRANT ALL ON FUNCTION public.set_lesson_break_strengths(p_lesson_id bigint, p_strengths jsonb) TO service_role;


-- Translating's write: fill translation on a slice of sentences, keyed by ordinal.
-- Touches only the translation column, leaving every other field intact.
CREATE FUNCTION public.set_lesson_translations(p_lesson_id bigint, p_translations jsonb) RETURNS void
    LANGUAGE sql
    AS $$
  update public.lesson_sentences ls
     set translation = t.translation
    from jsonb_to_recordset(p_translations) as t(ordinal integer, translation text)
   where ls.lesson_id = p_lesson_id and ls.ordinal = t.ordinal;
$$;


ALTER FUNCTION public.set_lesson_translations(p_lesson_id bigint, p_translations jsonb) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.set_lesson_translations(p_lesson_id bigint, p_translations jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_lesson_translations(p_lesson_id bigint, p_translations jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.set_lesson_translations(p_lesson_id bigint, p_translations jsonb) FROM authenticated;
GRANT ALL ON FUNCTION public.set_lesson_translations(p_lesson_id bigint, p_translations jsonb) TO service_role;


-- Transliterating's write: fill readings (one entry per word, index-aligned to the
-- sentence's `words`) on a slice, keyed by ordinal. Touches only the readings column.
CREATE FUNCTION public.set_lesson_readings(p_lesson_id bigint, p_readings jsonb) RETURNS void
    LANGUAGE sql
    AS $$
  update public.lesson_sentences ls
     set readings = r.readings
    from jsonb_to_recordset(p_readings) as r(ordinal integer, readings jsonb)
   where ls.lesson_id = p_lesson_id and ls.ordinal = r.ordinal;
$$;


ALTER FUNCTION public.set_lesson_readings(p_lesson_id bigint, p_readings jsonb) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.set_lesson_readings(p_lesson_id bigint, p_readings jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_lesson_readings(p_lesson_id bigint, p_readings jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.set_lesson_readings(p_lesson_id bigint, p_readings jsonb) FROM authenticated;
GRANT ALL ON FUNCTION public.set_lesson_readings(p_lesson_id bigint, p_readings jsonb) TO service_role;


CREATE FUNCTION public.invoke_lesson_process(p_lesson_id bigint) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_url         text;
  v_service_key text;
begin
  select decrypted_secret into v_url
  from vault.decrypted_secrets where name = 'supabase_url' limit 1;

  if v_url is null then
    raise exception
      'Vault secret "supabase_url" not found. '
      'Run: SELECT vault.create_secret(''<url>'', ''supabase_url'');';
  end if;

  select decrypted_secret into v_service_key
  from vault.decrypted_secrets where name = 'service_role_key' limit 1;

  if v_service_key is null then
    raise exception
      'Vault secret "service_role_key" not found. '
      'Run: SELECT vault.create_secret(''<key>'', ''service_role_key'');';
  end if;

  -- A phase (Whisper especially) runs well past pg_net's 5s default, so raise the
  -- timeout to the phase budget. We ignore the response either way -- the worker
  -- settles the row itself -- but this stops pg_net logging spurious timeouts and
  -- lets net._http_response capture the real result for debugging.
  perform net.http_post(
    url     := v_url || '/functions/v1/transcribe-lesson',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || v_service_key,
      'Content-Type',  'application/json'
    ),
    body    := jsonb_build_object('action', 'process', 'lesson_id', p_lesson_id),
    timeout_milliseconds := 150000
  );
end;
$$;


ALTER FUNCTION public.invoke_lesson_process(p_lesson_id bigint) OWNER TO postgres;


-- Cron/trigger entry point: SECURITY DEFINER with no caller check, because
-- pg_cron and the trigger both run as postgres. No client role gets EXECUTE
-- (see 20260807180000_lock-down-lesson-cron-functions).
REVOKE ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) FROM anon;
REVOKE ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) FROM authenticated;
REVOKE ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) FROM service_role;


CREATE FUNCTION public.reap_stalled_lessons() RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_reaped integer;
begin
  -- Leave phase (and chunk_cursor) intact so retry can resume from where the
  -- job died rather than re-transcribing from the start. A pre-resume failure
  -- has phase null and still restarts.
  update public.lessons
     set status     = 'failed',
         error_code = 'stalled',
         updated_at = now()
   where status = 'processing'
     and updated_at < now() - interval '10 minutes';

  get diagnostics v_reaped = row_count;
  return v_reaped;
end;
$$;


ALTER FUNCTION public.reap_stalled_lessons() OWNER TO postgres;


-- Cron/trigger entry point: SECURITY DEFINER with no caller check, because
-- pg_cron and the trigger both run as postgres. No client role gets EXECUTE
-- (see 20260807180000_lock-down-lesson-cron-functions).
REVOKE ALL ON FUNCTION public.reap_stalled_lessons() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reap_stalled_lessons() FROM anon;
REVOKE ALL ON FUNCTION public.reap_stalled_lessons() FROM authenticated;
REVOKE ALL ON FUNCTION public.reap_stalled_lessons() FROM service_role;


CREATE FUNCTION public.trigger_lesson_processing() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
begin
  if new.status = 'processing'
     and new.phase is not null
     and (tg_op = 'INSERT'
          or new.phase is distinct from old.phase
          or new.chunk_cursor is distinct from old.chunk_cursor
          -- Retry resume flips a failed row back to processing without moving
          -- phase or cursor, so the status flip is what re-fires the chain here.
          or old.status is distinct from new.status)
  then
    -- Side effect only: never let a failed kick abort the row write (see the
    -- original chain migration). The reaper settles the row if the kick is lost.
    begin
      perform public.invoke_lesson_process(new.id);
    exception
      when others then
        raise warning 'lesson % chain kick failed: %', new.id, sqlerrm;
    end;
  end if;
  return new;
end;
$$;


ALTER FUNCTION public.trigger_lesson_processing() OWNER TO postgres;


GRANT ALL ON FUNCTION public.trigger_lesson_processing() TO anon;
GRANT ALL ON FUNCTION public.trigger_lesson_processing() TO authenticated;
GRANT ALL ON FUNCTION public.trigger_lesson_processing() TO service_role;


CREATE TRIGGER lesson_processing_chain AFTER INSERT OR UPDATE ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.trigger_lesson_processing();


CREATE TRIGGER set_member_id_on_lesson BEFORE INSERT ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER set_member_id_on_lesson_collection BEFORE INSERT ON public.lesson_collections FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER trg_lesson_delete_soft_delete_media BEFORE DELETE ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.soft_delete_media_before_lesson_delete();


ALTER TABLE public.lesson_collections ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.lesson_sentences ENABLE ROW LEVEL SECURITY;


-- Read-only for the owning member; the worker writes through service_role, which
-- bypasses RLS, so there's no write policy for authenticated to hold.
CREATE POLICY lesson_sentences_owner_select ON public.lesson_sentences FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.lessons l
  WHERE ((l.id = lesson_sentences.lesson_id) AND (l.member_id = ( SELECT public.active_member_id() AS active_member_id))))));


CREATE POLICY lesson_collections_owner_delete ON public.lesson_collections FOR DELETE TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lesson_collections_owner_insert ON public.lesson_collections FOR INSERT TO authenticated WITH CHECK ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lesson_collections_owner_select ON public.lesson_collections FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lesson_collections_owner_update ON public.lesson_collections FOR UPDATE TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id)) WITH CHECK ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lessons_owner_delete ON public.lessons FOR DELETE TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lessons_owner_insert ON public.lessons FOR INSERT TO authenticated WITH CHECK ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lessons_owner_select ON public.lessons FOR SELECT TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id));


CREATE POLICY lessons_owner_update ON public.lessons FOR UPDATE TO authenticated USING ((( SELECT public.active_member_id() AS active_member_id) = member_id)) WITH CHECK ((( SELECT public.active_member_id() AS active_member_id) = member_id));


GRANT ALL ON TABLE public.lessons TO anon;
GRANT ALL ON TABLE public.lessons TO authenticated;
GRANT ALL ON TABLE public.lessons TO service_role;


GRANT ALL ON TABLE public.lesson_sentences TO anon;
GRANT ALL ON TABLE public.lesson_sentences TO authenticated;
GRANT ALL ON TABLE public.lesson_sentences TO service_role;


GRANT ALL ON TABLE public.lesson_collections TO anon;
GRANT ALL ON TABLE public.lesson_collections TO authenticated;
GRANT ALL ON TABLE public.lesson_collections TO service_role;


GRANT ALL ON SEQUENCE public.lesson_collections_id_seq TO anon;
GRANT ALL ON SEQUENCE public.lesson_collections_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.lesson_collections_id_seq TO service_role;


GRANT ALL ON TABLE public.lesson_collections_with_counts TO anon;
GRANT ALL ON TABLE public.lesson_collections_with_counts TO authenticated;
GRANT ALL ON TABLE public.lesson_collections_with_counts TO service_role;


GRANT ALL ON SEQUENCE public.lessons_id_seq TO anon;
GRANT ALL ON SEQUENCE public.lessons_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.lessons_id_seq TO service_role;
