-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    audio_path text NOT NULL,
    transcript jsonb DEFAULT '{}'::jsonb NOT NULL,
    lang text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    collection_id bigint NOT NULL,
    status text DEFAULT 'ready'::text NOT NULL,
    error_code text,
    phase text,
    script text DEFAULT 'original'::text NOT NULL,
    "position" numeric NOT NULL,
    chunks jsonb DEFAULT '[]'::jsonb NOT NULL,
    chunk_cursor integer DEFAULT 0 NOT NULL,
    CONSTRAINT lessons_status_check CHECK ((status = ANY (ARRAY['processing'::text, 'ready'::text, 'failed'::text])))
);


ALTER TABLE public.lessons OWNER TO postgres;


CREATE TABLE public.lesson_collections (
    id bigint NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_lesson_id bigint,
    last_position_seconds double precision DEFAULT 0 NOT NULL
);


ALTER TABLE public.lesson_collections OWNER TO postgres;


ALTER TABLE public.lesson_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_last_lesson_id_fkey FOREIGN KEY (last_lesson_id) REFERENCES public.lessons(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.lesson_collections
    ADD CONSTRAINT lesson_collections_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.lesson_collections(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);


CREATE INDEX lesson_collections_member_id_created_at_idx ON public.lesson_collections USING btree (member_id, created_at DESC);


CREATE INDEX lessons_collection_id_position_idx ON public.lessons USING btree (collection_id, "position");


CREATE VIEW public.lesson_collections_with_counts WITH (security_invoker='true') AS
 SELECT lc.id,
    lc.member_id,
    lc.title,
    lc.last_lesson_id,
    lc.last_position_seconds,
    lc.created_at,
    lc.updated_at,
    ( SELECT (count(*))::integer AS count
           FROM public.lessons l
          WHERE (l.collection_id = lc.id)) AS lesson_count
   FROM public.lesson_collections lc;


ALTER TABLE public.lesson_collections_with_counts OWNER TO postgres;


CREATE FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text DEFAULT 'original'::text, p_lang text DEFAULT NULL::text, p_chunks jsonb DEFAULT '[]'::jsonb) RETURNS public.lessons
    LANGUAGE plpgsql
    AS $$
declare
  v_lesson public.lessons;
  v_position numeric;
  v_chunks jsonb;
begin
  -- Server-assigned chapter order within the collection (max + 1), same as cards.
  select coalesce(max("position"), 0) + 1
  into v_position
  from public.lessons
  where collection_id = p_collection_id;

  -- Empty manifest -> one chunk covering the whole file from offset 0.
  if p_chunks is null or jsonb_array_length(p_chunks) = 0 then
    v_chunks := jsonb_build_array(
      jsonb_build_object('path', p_audio_path, 'offset', 0)
    );
  else
    v_chunks := p_chunks;
  end if;

  insert into public.lessons
    (collection_id, title, audio_path, transcript, lang,
     status, phase, script, "position", chunks, chunk_cursor)
  values
    (p_collection_id, p_title, p_audio_path, '{}'::jsonb, p_lang,
     'processing', 'transcribing', p_script, v_position, v_chunks, 0)
  returning * into v_lesson;

  insert into public.media (bucket, path, lesson_id)
  values ('audio-lessons', p_audio_path, v_lesson.id);

  return v_lesson;
end;
$$;


ALTER FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_lang text, p_chunks jsonb) OWNER TO postgres;


GRANT ALL ON FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_lang text, p_chunks jsonb) TO anon;
GRANT ALL ON FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_lang text, p_chunks jsonb) TO authenticated;
GRANT ALL ON FUNCTION public.create_pending_lesson(p_collection_id bigint, p_title text, p_audio_path text, p_script text, p_lang text, p_chunks jsonb) TO service_role;


CREATE FUNCTION public.invoke_lesson_process(p_lesson_id bigint) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_url         text;
  v_service_key text;
begin
  select decrypted_secret into v_url
  from vault.decrypted_secrets where name = 'supabase_url' limit 1;

  if v_url is null then
    raise exception
      'Vault secret "supabase_url" not found. '
      'Run: SELECT vault.create_secret(''<url>'', ''supabase_url'');';
  end if;

  select decrypted_secret into v_service_key
  from vault.decrypted_secrets where name = 'service_role_key' limit 1;

  if v_service_key is null then
    raise exception
      'Vault secret "service_role_key" not found. '
      'Run: SELECT vault.create_secret(''<key>'', ''service_role_key'');';
  end if;

  -- A phase (Whisper especially) runs well past pg_net's 5s default, so raise the
  -- timeout to the phase budget. We ignore the response either way -- the worker
  -- settles the row itself -- but this stops pg_net logging spurious timeouts and
  -- lets net._http_response capture the real result for debugging.
  perform net.http_post(
    url     := v_url || '/functions/v1/transcribe-lesson',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || v_service_key,
      'Content-Type',  'application/json'
    ),
    body    := jsonb_build_object('action', 'process', 'lesson_id', p_lesson_id),
    timeout_milliseconds := 150000
  );
end;
$$;


ALTER FUNCTION public.invoke_lesson_process(p_lesson_id bigint) OWNER TO postgres;


GRANT ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) TO anon;
GRANT ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) TO authenticated;
GRANT ALL ON FUNCTION public.invoke_lesson_process(p_lesson_id bigint) TO service_role;


CREATE FUNCTION public.reap_stalled_lessons() RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_reaped integer;
begin
  update public.lessons
     set status     = 'failed',
         phase      = null,
         error_code = 'stalled',
         updated_at = now()
   where status = 'processing'
     and updated_at < now() - interval '10 minutes';

  get diagnostics v_reaped = row_count;
  return v_reaped;
end;
$$;


ALTER FUNCTION public.reap_stalled_lessons() OWNER TO postgres;


GRANT ALL ON FUNCTION public.reap_stalled_lessons() TO anon;
GRANT ALL ON FUNCTION public.reap_stalled_lessons() TO authenticated;
GRANT ALL ON FUNCTION public.reap_stalled_lessons() TO service_role;


CREATE FUNCTION public.trigger_lesson_processing() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
begin
  if new.status = 'processing'
     and new.phase is not null
     and (tg_op = 'INSERT'
          or new.phase is distinct from old.phase
          or new.chunk_cursor is distinct from old.chunk_cursor)
  then
    -- Side effect only: never let a failed kick abort the row write (see the
    -- original chain migration). The reaper settles the row if the kick is lost.
    begin
      perform public.invoke_lesson_process(new.id);
    exception
      when others then
        raise warning 'lesson % chain kick failed: %', new.id, sqlerrm;
    end;
  end if;
  return new;
end;
$$;


ALTER FUNCTION public.trigger_lesson_processing() OWNER TO postgres;


GRANT ALL ON FUNCTION public.trigger_lesson_processing() TO anon;
GRANT ALL ON FUNCTION public.trigger_lesson_processing() TO authenticated;
GRANT ALL ON FUNCTION public.trigger_lesson_processing() TO service_role;


CREATE TRIGGER lesson_processing_chain AFTER INSERT OR UPDATE ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.trigger_lesson_processing();


CREATE TRIGGER set_member_id_on_lesson BEFORE INSERT ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER set_member_id_on_lesson_collection BEFORE INSERT ON public.lesson_collections FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER trg_lesson_delete_soft_delete_media BEFORE DELETE ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.soft_delete_media_before_lesson_delete();


ALTER TABLE public.lesson_collections ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;


CREATE POLICY lesson_collections_owner_delete ON public.lesson_collections FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lesson_collections_owner_insert ON public.lesson_collections FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lesson_collections_owner_select ON public.lesson_collections FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lesson_collections_owner_update ON public.lesson_collections FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lessons_owner_delete ON public.lessons FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lessons_owner_insert ON public.lessons FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lessons_owner_select ON public.lessons FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY lessons_owner_update ON public.lessons FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = member_id));


GRANT ALL ON TABLE public.lessons TO anon;
GRANT ALL ON TABLE public.lessons TO authenticated;
GRANT ALL ON TABLE public.lessons TO service_role;


GRANT ALL ON TABLE public.lesson_collections TO anon;
GRANT ALL ON TABLE public.lesson_collections TO authenticated;
GRANT ALL ON TABLE public.lesson_collections TO service_role;


GRANT ALL ON SEQUENCE public.lesson_collections_id_seq TO anon;
GRANT ALL ON SEQUENCE public.lesson_collections_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.lesson_collections_id_seq TO service_role;


GRANT ALL ON TABLE public.lesson_collections_with_counts TO anon;
GRANT ALL ON TABLE public.lesson_collections_with_counts TO authenticated;
GRANT ALL ON TABLE public.lesson_collections_with_counts TO service_role;


GRANT ALL ON SEQUENCE public.lessons_id_seq TO anon;
GRANT ALL ON SEQUENCE public.lessons_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.lessons_id_seq TO service_role;
