-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TYPE public.shop_category AS ENUM (
    'power_ups',
    'stationary'
);


ALTER TYPE public.shop_category OWNER TO postgres;


CREATE TABLE public.shop_items (
    id bigint NOT NULL,
    name text,
    item_key text,
    description text,
    price smallint,
    category public.shop_category
);


ALTER TABLE public.shop_items OWNER TO postgres;


ALTER TABLE public.shop_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.plans (
    id text NOT NULL,
    stripe_price_id text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cards_per_deck_limit integer,
    deck_limit integer
);


ALTER TABLE public.plans OWNER TO postgres;


CREATE TABLE public.purchases (
    id bigint NOT NULL,
    member_id uuid,
    item_id bigint,
    quantity smallint
);


ALTER TABLE public.purchases OWNER TO postgres;


ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.shop_items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_stripe_price_id_key UNIQUE (stripe_price_id);


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT unique_member_item UNIQUE (member_id, item_id);


ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_plan_fkey FOREIGN KEY (plan) REFERENCES public.plans(id);


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.shop_items(id) ON UPDATE RESTRICT;


ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE RESTRICT ON DELETE CASCADE;


CREATE INDEX purchases_member_id_idx ON public.purchases USING btree (member_id);


CREATE FUNCTION public.add_or_update_purchase(member uuid, item integer, qty integer) RETURNS void
    LANGUAGE plpgsql
    AS $$BEGIN
    INSERT INTO purchases (member_id, item_id, quantity)
    VALUES (member, item, qty)
    ON CONFLICT (member_id, item_id)
    DO UPDATE SET
        quantity = purchases.quantity + EXCLUDED.quantity;
END;$$;


ALTER FUNCTION public.add_or_update_purchase(member uuid, item integer, qty integer) OWNER TO postgres;


GRANT ALL ON FUNCTION public.add_or_update_purchase(member uuid, item integer, qty integer) TO anon;
GRANT ALL ON FUNCTION public.add_or_update_purchase(member uuid, item integer, qty integer) TO authenticated;
GRANT ALL ON FUNCTION public.add_or_update_purchase(member uuid, item integer, qty integer) TO service_role;


ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.shop_items ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable insert for users based on user_id" ON public.purchases FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "Enable read access for all users" ON public.shop_items FOR SELECT USING (true);


CREATE POLICY "Enable users to view their own data only" ON public.purchases FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "members can update their own purchases" ON public.purchases FOR UPDATE TO authenticated USING ((auth.uid() = member_id));


CREATE POLICY "plans readable by authenticated users" ON public.plans FOR SELECT TO authenticated USING ((is_active = true));


GRANT ALL ON TABLE public.shop_items TO anon;
GRANT ALL ON TABLE public.shop_items TO authenticated;
GRANT ALL ON TABLE public.shop_items TO service_role;


GRANT ALL ON SEQUENCE public.items_id_seq TO anon;
GRANT ALL ON SEQUENCE public.items_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.items_id_seq TO service_role;


GRANT ALL ON TABLE public.plans TO anon;
GRANT ALL ON TABLE public.plans TO authenticated;
GRANT ALL ON TABLE public.plans TO service_role;


GRANT ALL ON TABLE public.purchases TO anon;
GRANT ALL ON TABLE public.purchases TO authenticated;
GRANT ALL ON TABLE public.purchases TO service_role;


GRANT ALL ON SEQUENCE public.purchases_id_seq TO anon;
GRANT ALL ON SEQUENCE public.purchases_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.purchases_id_seq TO service_role;


COMMENT ON TABLE public.shop_items IS 'Items purchasable in the shop';


COMMENT ON TABLE public.purchases IS 'Junction table to link members to their purchased items';
