-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TYPE public.feedback_status AS ENUM (
    'new',
    'accepted',
    'rejected',
    'in-progress',
    'done'
);


ALTER TYPE public.feedback_status OWNER TO postgres;


CREATE TYPE public.feedback_type AS ENUM (
    'idea',
    'bug',
    'other'
);


ALTER TYPE public.feedback_type OWNER TO postgres;


CREATE TYPE public.feedback_visibility AS ENUM (
    'public',
    'internal'
);


ALTER TYPE public.feedback_visibility OWNER TO postgres;


CREATE TABLE public.feedback_items (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_id uuid NOT NULL,
    title text NOT NULL,
    body text,
    type public.feedback_type NOT NULL,
    status public.feedback_status DEFAULT 'new'::public.feedback_status NOT NULL,
    visibility public.feedback_visibility DEFAULT 'internal'::public.feedback_visibility NOT NULL
);


ALTER TABLE public.feedback_items OWNER TO postgres;


ALTER TABLE public.feedback_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.feedback_votes (
    feedback_id bigint NOT NULL,
    member_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.feedback_votes OWNER TO postgres;


ALTER TABLE ONLY public.feedback_items
    ADD CONSTRAINT feedback_items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.feedback_votes
    ADD CONSTRAINT feedback_votes_pkey PRIMARY KEY (feedback_id, member_id);


ALTER TABLE ONLY public.feedback_items
    ADD CONSTRAINT feedback_items_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.feedback_votes
    ADD CONSTRAINT feedback_votes_feedback_id_fkey FOREIGN KEY (feedback_id) REFERENCES public.feedback_items(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.feedback_votes
    ADD CONSTRAINT feedback_votes_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


CREATE FUNCTION public.feedback_items_with_votes() RETURNS TABLE(id bigint, created_at timestamp with time zone, member_id uuid, member_display_name text, member_avatar text, title text, body text, type public.feedback_type, status public.feedback_status, visibility public.feedback_visibility, vote_count integer, voted_by_me boolean)
    LANGUAGE sql STABLE
    AS $$
  SELECT
    f.id,
    f.created_at,
    f.member_id,
    m.display_name AS member_display_name,
    m.cover_config->>'avatar' AS member_avatar,
    f.title,
    f.body,
    f.type,
    f.status,
    f.visibility,
    (SELECT count(*)::int FROM public.feedback_votes v WHERE v.feedback_id = f.id) AS vote_count,
    EXISTS (
      SELECT 1 FROM public.feedback_votes v
      WHERE v.feedback_id = f.id AND v.member_id = auth.uid()
    ) AS voted_by_me
  FROM public.feedback_items f
  LEFT JOIN public.members m ON m.id = f.member_id
$$;


ALTER FUNCTION public.feedback_items_with_votes() OWNER TO postgres;


GRANT ALL ON FUNCTION public.feedback_items_with_votes() TO anon;
GRANT ALL ON FUNCTION public.feedback_items_with_votes() TO authenticated;
GRANT ALL ON FUNCTION public.feedback_items_with_votes() TO service_role;


CREATE FUNCTION public.submit_feedback(p_title text, p_body text, p_type public.feedback_type) RETURNS public.feedback_items
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_item public.feedback_items;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_title IS NULL OR btrim(p_title) = '' THEN
    RAISE EXCEPTION 'Title is required';
  END IF;

  INSERT INTO public.feedback_items (title, body, type)
  VALUES (p_title, p_body, p_type)
  RETURNING * INTO v_item;

  RETURN v_item;
END;
$$;


ALTER FUNCTION public.submit_feedback(p_title text, p_body text, p_type public.feedback_type) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.submit_feedback(p_title text, p_body text, p_type public.feedback_type) FROM PUBLIC;
GRANT ALL ON FUNCTION public.submit_feedback(p_title text, p_body text, p_type public.feedback_type) TO authenticated;
GRANT ALL ON FUNCTION public.submit_feedback(p_title text, p_body text, p_type public.feedback_type) TO service_role;


CREATE FUNCTION public.toggle_feedback_vote(p_feedback_id bigint) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.feedback_votes
    WHERE feedback_id = p_feedback_id AND member_id = v_uid
  ) THEN
    DELETE FROM public.feedback_votes
    WHERE feedback_id = p_feedback_id AND member_id = v_uid;
    RETURN false;
  END IF;

  INSERT INTO public.feedback_votes (feedback_id, member_id)
  VALUES (p_feedback_id, v_uid);
  RETURN true;
END;
$$;


ALTER FUNCTION public.toggle_feedback_vote(p_feedback_id bigint) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.toggle_feedback_vote(p_feedback_id bigint) FROM PUBLIC;
GRANT ALL ON FUNCTION public.toggle_feedback_vote(p_feedback_id bigint) TO authenticated;
GRANT ALL ON FUNCTION public.toggle_feedback_vote(p_feedback_id bigint) TO service_role;


CREATE FUNCTION public.update_feedback_item(p_feedback_id bigint, p_status public.feedback_status, p_visibility public.feedback_visibility) RETURNS public.feedback_items
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_item public.feedback_items;
BEGIN
  IF NOT public.can_moderate_feedback() THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  UPDATE public.feedback_items
  SET status = p_status, visibility = p_visibility
  WHERE id = p_feedback_id
  RETURNING * INTO v_item;

  IF v_item IS NULL THEN
    RAISE EXCEPTION 'Feedback item % not found', p_feedback_id;
  END IF;

  RETURN v_item;
END;
$$;


ALTER FUNCTION public.update_feedback_item(p_feedback_id bigint, p_status public.feedback_status, p_visibility public.feedback_visibility) OWNER TO postgres;


REVOKE ALL ON FUNCTION public.update_feedback_item(p_feedback_id bigint, p_status public.feedback_status, p_visibility public.feedback_visibility) FROM PUBLIC;
GRANT ALL ON FUNCTION public.update_feedback_item(p_feedback_id bigint, p_status public.feedback_status, p_visibility public.feedback_visibility) TO authenticated;
GRANT ALL ON FUNCTION public.update_feedback_item(p_feedback_id bigint, p_status public.feedback_status, p_visibility public.feedback_visibility) TO service_role;


CREATE TRIGGER set_member_id_on_feedback_item BEFORE INSERT ON public.feedback_items FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER set_member_id_on_feedback_vote BEFORE INSERT ON public.feedback_votes FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


ALTER TABLE public.feedback_items ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.feedback_votes ENABLE ROW LEVEL SECURITY;


CREATE POLICY "members can delete their own feedback vote" ON public.feedback_votes FOR DELETE TO authenticated USING ((member_id = auth.uid()));


CREATE POLICY "members can insert their own feedback item" ON public.feedback_items FOR INSERT TO authenticated WITH CHECK ((member_id = auth.uid()));


CREATE POLICY "members can insert their own feedback vote" ON public.feedback_votes FOR INSERT TO authenticated WITH CHECK ((member_id = auth.uid()));


CREATE POLICY "members can read feedback votes" ON public.feedback_votes FOR SELECT TO authenticated USING (true);


CREATE POLICY "members can read public feedback items" ON public.feedback_items FOR SELECT TO authenticated USING (((visibility = 'public'::public.feedback_visibility) OR public.can_moderate_feedback() OR (member_id = auth.uid())));


CREATE POLICY "moderators can update feedback items" ON public.feedback_items FOR UPDATE TO authenticated USING (public.can_moderate_feedback()) WITH CHECK (public.can_moderate_feedback());


GRANT ALL ON TABLE public.feedback_items TO anon;
GRANT ALL ON TABLE public.feedback_items TO authenticated;
GRANT ALL ON TABLE public.feedback_items TO service_role;


GRANT ALL ON SEQUENCE public.feedback_items_id_seq TO anon;
GRANT ALL ON SEQUENCE public.feedback_items_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.feedback_items_id_seq TO service_role;


GRANT ALL ON TABLE public.feedback_votes TO anon;
GRANT ALL ON TABLE public.feedback_votes TO authenticated;
GRANT ALL ON TABLE public.feedback_votes TO service_role;
