-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TABLE public.deck_review_pacing (
    deck_id bigint NOT NULL,
    review_pacing_preset_id bigint,
    desired_retention_override integer,
    learning_steps_override text[],
    relearning_steps_override text[],
    has_max_reviews_override boolean DEFAULT false NOT NULL,
    max_reviews_per_day_override integer,
    has_max_new_override boolean DEFAULT false NOT NULL,
    max_new_per_day_override integer
);


ALTER TABLE public.deck_review_pacing OWNER TO postgres;


CREATE TABLE public.review_logs (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    card_id bigint NOT NULL,
    member_id uuid NOT NULL,
    rating smallint NOT NULL,
    state smallint NOT NULL,
    due timestamp with time zone NOT NULL,
    stability real,
    difficulty real,
    scheduled_days smallint,
    review timestamp with time zone NOT NULL
);


ALTER TABLE public.review_logs OWNER TO postgres;


ALTER TABLE public.review_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.review_pacing_presets (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    member_id uuid,
    name text NOT NULL,
    desired_retention integer NOT NULL,
    learning_steps text[] NOT NULL,
    relearning_steps text[] NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    max_reviews_per_day integer,
    max_new_per_day integer
);


ALTER TABLE public.review_pacing_presets OWNER TO postgres;


ALTER TABLE public.review_pacing_presets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_pacing_presets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.reviews (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    card_id bigint,
    member_id uuid,
    difficulty real,
    due timestamp with time zone DEFAULT now(),
    elapsed_days smallint,
    lapses smallint,
    last_review date,
    learning_steps smallint,
    reps smallint,
    scheduled_days smallint,
    stability real,
    state smallint DEFAULT 2 NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;


ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.deck_review_pacing
    ADD CONSTRAINT deck_review_pacing_pkey PRIMARY KEY (deck_id);


ALTER TABLE ONLY public.review_logs
    ADD CONSTRAINT review_logs_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.review_pacing_presets
    ADD CONSTRAINT review_pacing_presets_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT unique_review_per_user_card UNIQUE (card_id);


ALTER TABLE ONLY public.deck_review_pacing
    ADD CONSTRAINT deck_review_pacing_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.deck_review_pacing
    ADD CONSTRAINT deck_review_pacing_review_pacing_preset_id_fkey FOREIGN KEY (review_pacing_preset_id) REFERENCES public.review_pacing_presets(id) ON DELETE SET NULL;


ALTER TABLE ONLY public.review_logs
    ADD CONSTRAINT review_logs_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.review_logs
    ADD CONSTRAINT review_logs_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.review_pacing_presets
    ADD CONSTRAINT review_pacing_presets_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


CREATE UNIQUE INDEX one_system_review_pacing_preset ON public.review_pacing_presets USING btree (is_system) WHERE is_system;


CREATE INDEX review_logs_card_id_idx ON public.review_logs USING btree (card_id);


CREATE INDEX review_logs_member_id_idx ON public.review_logs USING btree (member_id, review DESC);


CREATE INDEX reviews_card_id_due_member_id_idx ON public.reviews USING btree (card_id, due, member_id);


CREATE TRIGGER set_member_id_on_review BEFORE INSERT ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


CREATE TRIGGER set_member_id_on_review_pacing_preset BEFORE INSERT ON public.review_pacing_presets FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


ALTER TABLE public.deck_review_pacing ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.review_logs ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.review_pacing_presets ENABLE ROW LEVEL SECURITY;


ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable insert for users based on user_id" ON public.reviews FOR INSERT TO authenticated WITH CHECK (( SELECT (auth.uid() = reviews.member_id)));


CREATE POLICY "Enable users to view their own data only" ON public.reviews FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "Members can insert their own review logs" ON public.review_logs FOR INSERT TO authenticated WITH CHECK ((auth.uid() = member_id));


CREATE POLICY "Members can view their own review logs" ON public.review_logs FOR SELECT TO authenticated USING ((auth.uid() = member_id));


CREATE POLICY "members can delete their own presets" ON public.review_pacing_presets FOR DELETE TO authenticated USING (((member_id = auth.uid()) AND (is_system = false)));


CREATE POLICY "members can insert their own presets" ON public.review_pacing_presets FOR INSERT TO authenticated WITH CHECK (((member_id = auth.uid()) AND (is_system = false)));


CREATE POLICY "members can read and write their own decks' pacing" ON public.deck_review_pacing TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.decks d
  WHERE ((d.id = deck_review_pacing.deck_id) AND (d.member_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM public.decks d
  WHERE ((d.id = deck_review_pacing.deck_id) AND (d.member_id = auth.uid())))));


CREATE POLICY "members can read their own or the system preset" ON public.review_pacing_presets FOR SELECT TO authenticated USING ((is_system OR (member_id = auth.uid())));


CREATE POLICY "members can update their own presets" ON public.review_pacing_presets FOR UPDATE TO authenticated USING (((member_id = auth.uid()) AND (is_system = false))) WITH CHECK (((member_id = auth.uid()) AND (is_system = false)));


CREATE POLICY "members can update their own reviews" ON public.reviews FOR UPDATE TO authenticated USING ((auth.uid() = member_id));


GRANT ALL ON TABLE public.deck_review_pacing TO anon;
GRANT ALL ON TABLE public.deck_review_pacing TO authenticated;
GRANT ALL ON TABLE public.deck_review_pacing TO service_role;


GRANT ALL ON TABLE public.review_logs TO anon;
GRANT ALL ON TABLE public.review_logs TO authenticated;
GRANT ALL ON TABLE public.review_logs TO service_role;


GRANT ALL ON SEQUENCE public.review_logs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.review_logs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.review_logs_id_seq TO service_role;


GRANT ALL ON TABLE public.review_pacing_presets TO anon;
GRANT ALL ON TABLE public.review_pacing_presets TO authenticated;
GRANT ALL ON TABLE public.review_pacing_presets TO service_role;


GRANT ALL ON SEQUENCE public.review_pacing_presets_id_seq TO anon;
GRANT ALL ON SEQUENCE public.review_pacing_presets_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.review_pacing_presets_id_seq TO service_role;


GRANT ALL ON TABLE public.reviews TO anon;
GRANT ALL ON TABLE public.reviews TO authenticated;
GRANT ALL ON TABLE public.reviews TO service_role;


GRANT ALL ON SEQUENCE public.reviews_id_seq TO anon;
GRANT ALL ON SEQUENCE public.reviews_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.reviews_id_seq TO service_role;
