-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TABLE public.decks (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    description text,
    is_public boolean DEFAULT false NOT NULL,
    title text,
    member_id uuid NOT NULL,
    tags text[],
    has_image boolean DEFAULT false,
    study_config jsonb,
    cover_config jsonb DEFAULT '{"palette": "blue", "pattern": "diagonal-stripes", "icon": "symbol-spades"}'::jsonb,
    card_attributes jsonb,
    rank numeric NOT NULL
);


ALTER TABLE public.decks OWNER TO postgres;


ALTER TABLE public.decks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Decks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.decks
    ADD CONSTRAINT "Decks_pkey" PRIMARY KEY (id);


ALTER TABLE ONLY public.decks
    ADD CONSTRAINT decks_id_key UNIQUE (id);


ALTER TABLE ONLY public.decks
    ADD CONSTRAINT decks_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


CREATE INDEX decks_id_is_public_idx ON public.decks USING btree (id, is_public);


CREATE INDEX decks_member_id_idx ON public.decks USING hash (member_id);


CREATE TRIGGER set_member_id_on_deck BEFORE INSERT ON public.decks FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


ALTER TABLE public.decks ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable delete for users based on user_id" ON public.decks FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "Enable insert for authenticated users only" ON public.decks FOR INSERT TO authenticated WITH CHECK ((auth.uid() = member_id));


CREATE POLICY "Enable update for authenticated users" ON public.decks FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = member_id));


CREATE POLICY "Read public decks or own decks" ON public.decks FOR SELECT USING (((is_public = true) OR (auth.uid() = member_id)));


GRANT ALL ON TABLE public.decks TO anon;
GRANT ALL ON TABLE public.decks TO authenticated;
GRANT ALL ON TABLE public.decks TO service_role;


GRANT ALL ON SEQUENCE public."Decks_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Decks_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Decks_id_seq" TO service_role;
