-- Hand-organized declarative schema (by domain). Edit freely — this file is the
-- canonical definition. Run `supabase db diff -f <name>` after editing to
-- produce the migration.
SET check_function_bodies = false;

CREATE TYPE public.card_state AS ENUM (
    'new',
    'learning',
    'young',
    'mature',
    'relearn'
);


ALTER TYPE public.card_state OWNER TO postgres;


CREATE TABLE public.cards (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    front_text text,
    back_text text,
    deck_id bigint,
    member_id uuid,
    rank numeric(20,6) NOT NULL,
    note text
);


ALTER TABLE public.cards OWNER TO postgres;


ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT "Cards_pkey" PRIMARY KEY (id);


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_id_key UNIQUE (id);


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.decks(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE;


CREATE INDEX cards_deck_front_back_text_idx ON public.cards USING btree (deck_id, front_text, back_text);


CREATE INDEX cards_deck_id_idx ON public.cards USING hash (deck_id);


CREATE INDEX cards_deck_rank_idx ON public.cards USING btree (deck_id, rank);


CREATE INDEX cards_member_id_idx ON public.cards USING hash (member_id);


CREATE TRIGGER set_member_id_on_card BEFORE INSERT ON public.cards FOR EACH ROW EXECUTE FUNCTION public.set_member_id();


ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable delete for users based on user_id" ON public.cards FOR DELETE TO authenticated USING ((auth.uid() = member_id));


CREATE POLICY "Enable insert for authenticated users only" ON public.cards FOR INSERT TO authenticated WITH CHECK ((auth.uid() = member_id));


CREATE POLICY "Read cards from public decks or own cards" ON public.cards FOR SELECT USING (((auth.uid() = member_id) OR (EXISTS ( SELECT 1
   FROM public.decks
  WHERE ((decks.id = cards.deck_id) AND (decks.is_public = true))))));


CREATE POLICY "Users can update their own cards" ON public.cards FOR UPDATE TO authenticated USING ((auth.uid() = member_id)) WITH CHECK ((auth.uid() = member_id));


GRANT ALL ON TABLE public.cards TO anon;
GRANT ALL ON TABLE public.cards TO authenticated;
GRANT ALL ON TABLE public.cards TO service_role;


GRANT ALL ON SEQUENCE public."Cards_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."Cards_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Cards_id_seq" TO service_role;
