-- Review Pacing presets: a per-member library of FSRS scheduling presets
-- (desired retention + learning/relearning steps), plus one system-owned
-- "recommended" preset every member can use but never edit/delete. Each deck
-- links to a preset directly (1:1) and may pin individual fields away from
-- it via its own *_override columns, resolved in decks_with_stats.

BEGIN;

CREATE TABLE public.review_pacing_presets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  member_id uuid REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE,
  name text NOT NULL,
  desired_retention integer NOT NULL,
  learning_steps text[] NOT NULL,
  relearning_steps text[] NOT NULL,
  is_system boolean NOT NULL DEFAULT false
);

-- At most one system-owned preset can exist. A partial unique index (the
-- WHERE clause) only enforces uniqueness across rows matching it, so
-- ordinary member rows (is_system = false) are untouched.
CREATE UNIQUE INDEX one_system_review_pacing_preset
  ON public.review_pacing_presets ((is_system))
  WHERE is_system;

ALTER TABLE public.decks
  ADD COLUMN review_pacing_preset_id bigint REFERENCES public.review_pacing_presets(id) ON DELETE SET NULL,
  ADD COLUMN desired_retention_override integer,
  ADD COLUMN learning_steps_override text[],
  ADD COLUMN relearning_steps_override text[];

ALTER TABLE public.review_pacing_presets ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER set_member_id_on_review_pacing_preset
  BEFORE INSERT ON public.review_pacing_presets
  FOR EACH ROW EXECUTE FUNCTION public.set_member_id();

CREATE POLICY "members can read their own or the system preset"
ON public.review_pacing_presets
FOR SELECT
TO authenticated
USING (is_system OR member_id = auth.uid());

CREATE POLICY "members can insert their own presets"
ON public.review_pacing_presets
FOR INSERT
TO authenticated
WITH CHECK (member_id = auth.uid() AND is_system = false);

CREATE POLICY "members can update their own presets"
ON public.review_pacing_presets
FOR UPDATE
TO authenticated
USING (member_id = auth.uid() AND is_system = false)
WITH CHECK (member_id = auth.uid() AND is_system = false);

CREATE POLICY "members can delete their own presets"
ON public.review_pacing_presets
FOR DELETE
TO authenticated
USING (member_id = auth.uid() AND is_system = false);

-- Seed the system preset. Values match today's member-preference defaults
-- (MEMBER_PREFERENCES_DEFAULTS.study in src/utils/member/preferences.ts) so
-- nothing changes for a member who never customized their scheduling.
INSERT INTO public.review_pacing_presets (member_id, name, desired_retention, learning_steps, relearning_steps, is_system)
VALUES (NULL, 'Recommended', 90, ARRAY['1m', '10m'], ARRAY['10m'], true);

COMMIT;
