-- Feedback board: members submit ideas/bugs, heart others' items, admins and
-- moderators triage. Mirrors the capability-function pattern from
-- 20260715000000_capability-functions.sql.

BEGIN;

CREATE TYPE feedback_type AS ENUM ('idea', 'bug', 'other');
CREATE TYPE feedback_status AS ENUM ('new', 'accepted', 'rejected', 'in-progress', 'done');
CREATE TYPE feedback_visibility AS ENUM ('public', 'internal');

CREATE TABLE public.feedback_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  member_id uuid NOT NULL REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE,
  title text NOT NULL,
  body text,
  type feedback_type NOT NULL,
  status feedback_status NOT NULL DEFAULT 'new',
  visibility feedback_visibility NOT NULL DEFAULT 'public'
);

CREATE TABLE public.feedback_votes (
  feedback_id bigint NOT NULL REFERENCES public.feedback_items(id) ON DELETE CASCADE,
  member_id uuid NOT NULL REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (feedback_id, member_id)
);

ALTER TABLE public.feedback_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback_votes ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER set_member_id_on_feedback_item
  BEFORE INSERT ON public.feedback_items
  FOR EACH ROW EXECUTE FUNCTION public.set_member_id();

CREATE TRIGGER set_member_id_on_feedback_vote
  BEFORE INSERT ON public.feedback_votes
  FOR EACH ROW EXECUTE FUNCTION public.set_member_id();

-- Capability: admin or moderator. First capability fn to diverge from plain
-- is_admin, and wires up the previously-unused `moderator` enum value.
CREATE OR REPLACE FUNCTION public.can_moderate_feedback()
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT auth_role() IN ('admin', 'moderator')
$$;

REVOKE ALL ON FUNCTION public.can_moderate_feedback() FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.can_moderate_feedback() TO authenticated;

-- RLS: public items are readable by anyone signed in; internal items and
-- full moderation access require the capability. Writes go through RPCs
-- below, not direct table access, but SELECT policies still gate reads.

CREATE POLICY "members can read public feedback items"
ON public.feedback_items
FOR SELECT
TO authenticated
USING (visibility = 'public' OR can_moderate_feedback());

CREATE POLICY "moderators can update feedback items"
ON public.feedback_items
FOR UPDATE
TO authenticated
USING (can_moderate_feedback())
WITH CHECK (can_moderate_feedback());

CREATE POLICY "members can read feedback votes"
ON public.feedback_votes
FOR SELECT
TO authenticated
USING (true);

-- submit_feedback: any authenticated member can create their own item.
CREATE OR REPLACE FUNCTION public.submit_feedback(
  p_title text,
  p_body text,
  p_type feedback_type
)
RETURNS public.feedback_items
LANGUAGE plpgsql
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_item public.feedback_items;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_title IS NULL OR btrim(p_title) = '' THEN
    RAISE EXCEPTION 'Title is required';
  END IF;

  INSERT INTO public.feedback_items (title, body, type)
  VALUES (p_title, p_body, p_type)
  RETURNING * INTO v_item;

  RETURN v_item;
END;
$$;

-- toggle_feedback_vote: one heart per member, un-heart allowed. Returns the
-- new voted state (true = now voted, false = now un-voted).
CREATE OR REPLACE FUNCTION public.toggle_feedback_vote(p_feedback_id bigint)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.feedback_votes
    WHERE feedback_id = p_feedback_id AND member_id = v_uid
  ) THEN
    DELETE FROM public.feedback_votes
    WHERE feedback_id = p_feedback_id AND member_id = v_uid;
    RETURN false;
  END IF;

  INSERT INTO public.feedback_votes (feedback_id, member_id)
  VALUES (p_feedback_id, v_uid);
  RETURN true;
END;
$$;

-- update_feedback_item: moderators/admins triage status/visibility.
-- RLS on the UPDATE policy above is the real gate; this raises a clearer
-- error than a silent "0 rows updated" when it's denied.
CREATE OR REPLACE FUNCTION public.update_feedback_item(
  p_feedback_id bigint,
  p_status feedback_status,
  p_visibility feedback_visibility
)
RETURNS public.feedback_items
LANGUAGE plpgsql
AS $$
DECLARE
  v_item public.feedback_items;
BEGIN
  IF NOT public.can_moderate_feedback() THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  UPDATE public.feedback_items
  SET status = p_status, visibility = p_visibility
  WHERE id = p_feedback_id
  RETURNING * INTO v_item;

  IF v_item IS NULL THEN
    RAISE EXCEPTION 'Feedback item % not found', p_feedback_id;
  END IF;

  RETURN v_item;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_feedback(text, text, feedback_type) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.submit_feedback(text, text, feedback_type) TO authenticated;

REVOKE ALL ON FUNCTION public.toggle_feedback_vote(bigint) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.toggle_feedback_vote(bigint) TO authenticated;

REVOKE ALL ON FUNCTION public.update_feedback_item(bigint, feedback_status, feedback_visibility) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.update_feedback_item(bigint, feedback_status, feedback_visibility) TO authenticated;

COMMIT;
