-- =============================================================================
-- Audio Reader: `lessons` table
-- =============================================================================
--
-- One row per uploaded audio lesson. The audio bytes live in the
-- `audio-lessons` storage bucket (next migration); this table holds the
-- metadata + the Whisper transcript.
--
-- `transcript` is jsonb so the timestamped segments stay queryable and diffable
-- without a child table:
--   { "text": "...", "segments": [ { "start": 0.0, "end": 2.4, "text": "..." } ] }
--
-- Ownership + isolation mirror `decks`: a BEFORE INSERT trigger stamps
-- member_id from auth.uid() (so the client never sends it), and four
-- owner-scoped RLS policies keep each member to their own rows.
-- =============================================================================

BEGIN;

create table "public"."lessons" (
  "id"         bigint generated by default as identity primary key,
  "member_id"  uuid not null references "public"."members" ("id") on delete cascade,
  "title"      text not null,
  "audio_path" text not null,
  "transcript" jsonb not null default '{}'::jsonb,
  "lang"       text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

-- Library list query is "my lessons, newest first" — a composite index on
-- (member_id, created_at DESC) serves both the filter and the sort.
create index "lessons_member_id_created_at_idx"
  on "public"."lessons" ("member_id", "created_at" desc);

-- Reuse the shared trigger that every owned table uses: it sets
-- new.member_id := auth.uid() before the row is written, so the FE inserts
-- without ever passing member_id. NOT NULL is still satisfied because BEFORE
-- triggers run before constraint checks.
create trigger "set_member_id_on_lesson"
  before insert on "public"."lessons"
  for each row execute function "public"."set_member_id"();

alter table "public"."lessons" enable row level security;

create policy "lessons_owner_select"
  on "public"."lessons"
  for select to authenticated
  using ((select auth.uid()) = member_id);

create policy "lessons_owner_insert"
  on "public"."lessons"
  for insert to authenticated
  with check ((select auth.uid()) = member_id);

create policy "lessons_owner_update"
  on "public"."lessons"
  for update to authenticated
  using ((select auth.uid()) = member_id)
  with check ((select auth.uid()) = member_id);

create policy "lessons_owner_delete"
  on "public"."lessons"
  for delete to authenticated
  using ((select auth.uid()) = member_id);

grant all on table "public"."lessons" to "authenticated";
grant all on table "public"."lessons" to "service_role";

COMMIT;
