-- =============================================================================
-- Audio Reader: `lesson_collections` + group existing lessons under one
-- =============================================================================
--
-- Lessons stop being a flat per-member list and become children of a
-- collection (deck → cards, but collection → lessons). One row per collection.
--
-- This migration also backfills: every existing lesson is reparented into a
-- single default "Lessons" collection owned by the same member, so the new
-- NOT NULL `lessons.collection_id` is satisfiable for rows that predate it.
--
-- Ownership + isolation mirror `lessons` / `decks`: a BEFORE INSERT trigger
-- stamps member_id from auth.uid(), and four owner-scoped RLS policies keep
-- each member to their own rows.
-- =============================================================================

BEGIN;

create table "public"."lesson_collections" (
  "id"         bigint generated by default as identity primary key,
  "member_id"  uuid not null references "public"."members" ("id") on delete cascade,
  "title"      text not null,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

-- Library list query is "my collections, newest first" — composite index on
-- (member_id, created_at DESC) serves both the filter and the sort.
create index "lesson_collections_member_id_created_at_idx"
  on "public"."lesson_collections" ("member_id", "created_at" desc);

-- Same shared trigger every owned table uses: sets new.member_id := auth.uid()
-- before the row is written, so the FE never passes member_id.
create trigger "set_member_id_on_lesson_collection"
  before insert on "public"."lesson_collections"
  for each row execute function "public"."set_member_id"();

alter table "public"."lesson_collections" enable row level security;

create policy "lesson_collections_owner_select"
  on "public"."lesson_collections"
  for select to authenticated
  using ((select auth.uid()) = member_id);

create policy "lesson_collections_owner_insert"
  on "public"."lesson_collections"
  for insert to authenticated
  with check ((select auth.uid()) = member_id);

create policy "lesson_collections_owner_update"
  on "public"."lesson_collections"
  for update to authenticated
  using ((select auth.uid()) = member_id)
  with check ((select auth.uid()) = member_id);

create policy "lesson_collections_owner_delete"
  on "public"."lesson_collections"
  for delete to authenticated
  using ((select auth.uid()) = member_id);

grant all on table "public"."lesson_collections" to "authenticated";
grant all on table "public"."lesson_collections" to "service_role";

-- ---------------------------------------------------------------------------
-- Reparent existing lessons
-- ---------------------------------------------------------------------------

-- Add the link column nullable first — existing rows have no collection yet, so
-- a NOT NULL column couldn't be added until after the backfill below.
alter table "public"."lessons"
  add column "collection_id" bigint;

-- The set_member_id trigger UNCONDITIONALLY assigns member_id := auth.uid().
-- Here we run as the migration role, where auth.uid() is NULL, so leaving the
-- trigger on would clobber the explicit member_id we SELECT from `lessons` and
-- the NOT NULL constraint would fail. Disable it for the bulk insert only.
alter table "public"."lesson_collections"
  disable trigger "set_member_id_on_lesson_collection";

-- One default collection per member who owns lessons, then point that member's
-- lessons at it. The INSERT's RETURNING feeds the UPDATE in the same statement
-- (a data-modifying CTE), so we map lessons to the collection by the freshly
-- generated id — titles aren't unique, member_id is the join key.
with new_collections as (
  insert into "public"."lesson_collections" (member_id, title)
  select distinct member_id, 'Lessons'
  from "public"."lessons"
  returning id, member_id
)
update "public"."lessons" l
set collection_id = nc.id
from new_collections nc
where nc.member_id = l.member_id;

alter table "public"."lesson_collections"
  enable trigger "set_member_id_on_lesson_collection";

-- Now every lesson has a collection — lock the invariant in: NOT NULL + an FK
-- that cascades (deleting a collection deletes its lessons, like deck → cards)
-- + an index for the "lessons in this collection" list query.
alter table "public"."lessons"
  alter column "collection_id" set not null;

alter table "public"."lessons"
  add constraint "lessons_collection_id_fkey"
  foreign key (collection_id) references "public"."lesson_collections" ("id")
  on delete cascade;

create index "lessons_collection_id_idx"
  on "public"."lessons" ("collection_id");

COMMIT;
