-- knowledge: reward_rules, member_rewards, credit_occasion_reward — corpus/rewards/rewards.md

  create table "public"."reward_rules" (
    "id" bigint generated by default as identity not null,
    "key" text not null,
    "scope" text not null,
    "resolver" text not null,
    "params" jsonb not null,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."reward_rules" enable row level security;

alter table "public"."member_rewards" add column "occasion_ref" text;

alter table "public"."member_rewards" add column "reward_rule_id" bigint;

alter table "public"."member_rewards" alter column "reward_milestone_id" drop not null;

CREATE UNIQUE INDEX member_rewards_member_rule_occasion_key ON public.member_rewards USING btree (member_id, reward_rule_id, occasion_ref) WHERE (reward_rule_id IS NOT NULL);

CREATE UNIQUE INDEX reward_rules_key_key ON public.reward_rules USING btree (key);

CREATE UNIQUE INDEX reward_rules_pkey ON public.reward_rules USING btree (id);

alter table "public"."reward_rules" add constraint "reward_rules_pkey" PRIMARY KEY using index "reward_rules_pkey";

alter table "public"."member_rewards" add constraint "member_rewards_grant_target_chk" CHECK (((reward_milestone_id IS NOT NULL) <> (reward_rule_id IS NOT NULL))) not valid;

alter table "public"."member_rewards" validate constraint "member_rewards_grant_target_chk";

alter table "public"."member_rewards" add constraint "member_rewards_reward_rule_id_fkey" FOREIGN KEY (reward_rule_id) REFERENCES public.reward_rules(id) not valid;

alter table "public"."member_rewards" validate constraint "member_rewards_reward_rule_id_fkey";

alter table "public"."reward_rules" add constraint "reward_rules_key_key" UNIQUE using index "reward_rules_key_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.credit_occasion_reward(p_member uuid, p_rule_key text, p_occasion_ref text, p_count bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_rule   public.reward_rules%ROWTYPE;
  v_amount bigint;
  v_grant  bigint;
BEGIN
  SELECT * INTO v_rule
    FROM public.reward_rules
   WHERE key = p_rule_key AND is_active;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown or inactive reward rule: %', p_rule_key;
  END IF;

  IF v_rule.resolver = 'curve' THEN
    v_amount := round(
      (v_rule.params ->> 'max_bonus')::numeric
      * (1 - power((v_rule.params ->> 'decay')::numeric, p_count::numeric))
    )::bigint;
  ELSE
    RAISE EXCEPTION 'Unknown resolver kind: %', v_rule.resolver;
  END IF;

  IF v_amount <= 0 THEN
    RETURN;
  END IF;

  INSERT INTO public.member_rewards (member_id, reward_rule_id, occasion_ref)
  VALUES (p_member, v_rule.id, p_occasion_ref)
  ON CONFLICT (member_id, reward_rule_id, occasion_ref) WHERE reward_rule_id IS NOT NULL DO NOTHING
  RETURNING id INTO v_grant;

  IF v_grant IS NULL THEN
    RETURN;
  END IF;

  PERFORM public.apply_reward(
    p_member,
    jsonb_build_array(jsonb_build_object('kind', 'paperclips', 'amount', v_amount)),
    v_grant
  );
END;
$function$
;

revoke all on function public.credit_occasion_reward(p_member uuid, p_rule_key text, p_occasion_ref text, p_count bigint) from public;
revoke all on function public.credit_occasion_reward(p_member uuid, p_rule_key text, p_occasion_ref text, p_count bigint) from anon;
revoke all on function public.credit_occasion_reward(p_member uuid, p_rule_key text, p_occasion_ref text, p_count bigint) from authenticated;
grant all on function public.credit_occasion_reward(p_member uuid, p_rule_key text, p_occasion_ref text, p_count bigint) to service_role;

grant delete on table "public"."reward_rules" to "anon";

grant insert on table "public"."reward_rules" to "anon";

grant references on table "public"."reward_rules" to "anon";

grant select on table "public"."reward_rules" to "anon";

grant trigger on table "public"."reward_rules" to "anon";

grant truncate on table "public"."reward_rules" to "anon";

grant update on table "public"."reward_rules" to "anon";

grant delete on table "public"."reward_rules" to "authenticated";

grant insert on table "public"."reward_rules" to "authenticated";

grant references on table "public"."reward_rules" to "authenticated";

grant select on table "public"."reward_rules" to "authenticated";

grant trigger on table "public"."reward_rules" to "authenticated";

grant truncate on table "public"."reward_rules" to "authenticated";

grant update on table "public"."reward_rules" to "authenticated";

grant delete on table "public"."reward_rules" to "service_role";

grant insert on table "public"."reward_rules" to "service_role";

grant references on table "public"."reward_rules" to "service_role";

grant select on table "public"."reward_rules" to "service_role";

grant trigger on table "public"."reward_rules" to "service_role";

grant truncate on table "public"."reward_rules" to "service_role";

grant update on table "public"."reward_rules" to "service_role";


  create policy "active rules readable by authenticated users"
  on "public"."reward_rules"
  as permissive
  for select
  to authenticated
using ((is_active = true));


insert into public.reward_rules (key, scope, resolver, params, is_active)
values ('study.session_completion_bonus', 'session', 'curve', '{"max_bonus": 30, "decay": 0.98}'::jsonb, true)
on conflict (key) do nothing;



